import { useEffect, useRef, useState } from 'react';
import type { ReadableCollaborationEntry } from '../../src/client/collaboration-crypto.js';
import { useApp } from '../shared/context';
import { Avatar, Button, EmptyState, ErrorNotice, Field, Modal, Spinner, Textarea } from '../shared/ui';
import { editable, has, text, useAction } from './shared';
import type { Project } from './shared';

export function Discussion({project,taskId,phaseId}:{project:Project;taskId?:string;phaseId?:string}){
 const {client,directory}=useApp(),projectId=project.graph.project.id,kind=taskId?'comment':'update';
 const [entries,setEntries]=useState<ReadableCollaborationEntry[]>([]),[cursor,setCursor]=useState<string|null>(null),[anchor,setAnchor]=useState<string|undefined>(),[loading,setLoading]=useState(true),[error,setError]=useState<unknown>(null),[draft,setDraft]=useState(''),[hidden,setHidden]=useState<ReadableCollaborationEntry|null>(null),[reason,setReason]=useState(''),[includeHidden,setIncludeHidden]=useState(false);const action=useAction(),request=useRef(0),mounted=useRef(true);
 const task=taskId?project.graph.tasks.find(row=>row.id===taskId):undefined;
 const writable=has(project,'comment')&&editable(project,task?.phaseId??phaseId)&&(!task||!['done','cancelled'].includes(task.state));
 const moderate=has(project,taskId?'manage_tasks':'plan_projects');
 async function load(more=false){const revision=++request.current;setLoading(true);try{const page=await client.collaboration.read({projectId,kind,includeHidden,...(taskId?{taskId}:{}),...(phaseId?{phaseId}:{}),...(more&&cursor?{after:cursor}:{}),...(more&&anchor?{anchor}:{}),limit:50});if(!mounted.current||request.current!==revision)return;setEntries(previous=>more?[...previous,...page.records]:page.records);setCursor(page.nextCursor);setAnchor(page.anchor);setError(null);}catch(value){if(mounted.current&&request.current===revision)setError(value);}finally{if(mounted.current&&request.current===revision)setLoading(false);}}
 useEffect(()=>{mounted.current=true;let active=true;setEntries([]);setCursor(null);setAnchor(undefined);void load();const refresh=()=>{if(active&&document.visibilityState==='visible')void load();};window.addEventListener('focus',refresh);const timer=setInterval(refresh,60_000);return()=>{active=false;mounted.current=false;request.current++;window.removeEventListener('focus',refresh);clearInterval(timer);};},[projectId,taskId,phaseId,client,includeHidden]);
 async function post(){const operationId=crypto.randomUUID();await action.run(taskId?'Comment added':'Update shared',()=>taskId?client.collaboration.postComment({projectId,taskId,text:draft,operationId}):client.collaboration.postUpdate({projectId,...(phaseId?{phaseId}:{}),text:draft,operationId}),()=>client.collaboration.resume(operationId),async()=>{setDraft('');await load();});}
 async function hide(){if(!hidden)return;const operationId=crypto.randomUUID();await action.run('Entry hidden',()=>client.collaboration.hide({projectId,kind,entryId:hidden.entryId,reason,reviewed:{revision:hidden.pin.revision,head:hidden.pin.head},operationId}),()=>client.collaboration.resume(operationId),async()=>{setHidden(null);setReason('');await load();});}
 return <div className="discussion stack">{writable&&<form className="form-stack" onSubmit={event=>{event.preventDefault();void post();}}><Field label={taskId?'Add to the conversation':'Share an update'}><Textarea required maxLength={20000} value={draft} onChange={event=>setDraft(event.target.value)} rows={3} placeholder={taskId?'Ask a question or share progress…':'What should the team know?'}/></Field><div className="button-row"><Button type="submit" busy={action.busy}>{taskId?'Post comment':'Share update'}</Button></div></form>}{action.feedback}{Boolean(error)&&<ErrorNotice error={error} retry={()=>void load()}/>}<label className="check-row muted"><input type="checkbox" checked={includeHidden} onChange={event=>setIncludeHidden(event.target.checked)}/>Include hidden history</label><div className="discussion-feed">{[...entries].sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.entryId.localeCompare(b.entryId)).map(entry=>{const person=directory?.people.find(row=>row.accountId===entry.authorId);return <article className="discussion-entry" key={entry.entryId}><Avatar selection={person?.avatar} name={person?.displayName??'Former member'} size={34}/><div className="discussion-body"><div className="section-heading"><div><strong>{person?.displayName??'Former member'}</strong><time dateTime={entry.createdAt} className="discussion-time">{new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(entry.createdAt))}</time></div>{moderate&&!entry.hidden&&<Button variant="ghost" onClick={()=>{setHidden(entry);setReason('');}}>Hide</Button>}</div><p className="preserve-lines">{entry.text}</p>{entry.moderation&&<p className="muted">Hidden: {entry.moderation.reason}</p>}</div></article>;})}</div>{loading&&<Spinner/>}{!loading&&!error&&!entries.length&&<EmptyState title={taskId?'Start the conversation':'Room for your first update'} description={writable?'A short note can keep everyone moving together.':'Updates will appear here as the team makes progress.'}/>}<div className="button-row">{cursor&&<Button variant="secondary" busy={loading} onClick={()=>void load(true)}>Load more entries</Button>}<Button variant="ghost" busy={loading} onClick={()=>void load()}>Refresh</Button></div>{hidden&&<Modal open title="Hide this entry?" description="The original remains in the project history." onClose={()=>setHidden(null)}><form className="form-stack" onSubmit={event=>{event.preventDefault();void hide();}}><p className="quote">{hidden.text}</p><Field label="Reason"><Textarea autoFocus required maxLength={20000} value={reason} onChange={event=>setReason(event.target.value)}/></Field>{action.feedback}<div className="button-row"><Button variant="ghost" onClick={()=>setHidden(null)}>Go back</Button><Button type="submit" variant="danger" busy={action.busy}>Hide entry</Button></div></form></Modal>}</div>;
}
export function Activity({project}:{project:Project}){const {directory}=useApp();return <div className="activity-list">{[...project.audits].reverse().map(entry=>{const person=directory?.people.find(row=>row.accountId===entry.actorId);return <article className="activity-entry" key={entry.id}><span className="activity-dot"/><div><p><strong>{person?.displayName??'Former member'}</strong> {activityLabel(entry.data.action)}</p><time className="muted">{new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(entry.signedAt))}</time>{entry.data.changed.filter(change=>JSON.stringify(change.before)!==JSON.stringify(change.after)).map(change=><details key={`${change.kind}:${change.id}`}><summary>{text(change.after.title)||text(change.after.name)||'Details'}</summary>{Object.entries(change.after).filter(([,value])=>typeof value==='string').map(([key,value])=><p className="preserve-lines" key={key}><strong>{({name:'Name',title:'Task',description:'Description',objective:'Objective',completionCriteria:'Completion criteria',acceptanceCriteria:'Acceptance criteria',startDate:'Start date',dueDate:'Due date',priority:'Priority',reason:'Reason',nextAction:'Next action'} as Record<string,string>)[key]??'Detail'}:</strong> {String(value)}</p>)}</details>)}{entry.outcome&&<p className="preserve-lines">{entry.outcome}</p>}</div></article>;})}{!project.audits.length&&<EmptyState title="Your story starts here" description="Project changes will appear here as work moves forward."/>}</div>;}

function activityLabel(action:string){return ({edit_project:'updated the project',start_project:'started the project',complete_project:'completed the project',cancel_project:'cancelled the project',reopen_project:'reopened the project',archive_project:'archived the project',unarchive_project:'restored the project from archive',create_phase:'added a new phase of work',edit_phase:'updated a phase of work',start_phase:'started a phase of work',complete_phase:'completed a phase of work',cancel_phase:'cancelled a phase of work',reopen_phase:'reopened a phase of work',archive_phase:'archived a phase of work',unarchive_phase:'restored a phase from archive',create_milestone:'added a milestone',edit_milestone:'updated a milestone',accept_milestone:'accepted a milestone',cancel_milestone:'cancelled a milestone',reopen_milestone:'reopened a milestone',create_task:'added a task',edit_task:'updated a task',assign_task:'updated task assignees',start_task:'started a task',set_task_todo:'moved a task to To do',request_task_completion:'finished work on a task',approve_task:'approved a task',reject_task:'requested changes',cancel_task:'cancelled a task',reopen_task:'reopened a task',restore_task:'restored a task',select_task_reviewer:'updated the reviewer',set_project_review:'changed the task review preference',carry_task:'moved a task',create_blocker:'added a blocker',edit_blocker:'updated a blocker',resolve_blocker:'resolved a blocker',reopen_blocker:'reopened a blocker',upgrade_content:'updated the workspace'} as Record<string,string>)[action]??'updated the project';}
