'use client';
import { useEffect, useState } from 'react';
import { Download, Trash2, RefreshCw, ShieldCheck, Check } from 'lucide-react';
import { useApp } from '../shared/context';
import { Badge, Button, EmptyState, Field, Input, PageHead, Select } from '../shared/ui';
import type { ReportingSettingsPin } from '../../src/client/reporting-settings-crypto.js';
import type { ReadableRestoration } from '../../src/client/restoration-crypto.js';
import { contentSchemaRegistry } from '../../src/shared/content-schema.js';
import { CheckOption, dateLabel, LoadState, Panel, PasswordRefresh, SecureConfirm, useSettingsLoad, workspaceEditable } from './common';
const currentContentSchema = Math.max(...Object.keys(contentSchemaRegistry).map(Number));
export function WorkspaceSettings() {
  const { client, directory, theme, setTheme } = useApp(); const data = useSettingsLoad(() => client.reporting.settings());
  const [review, setReview] = useState<{ pin: ReportingSettingsPin; before: string | null; after: string }>();
  const zones = typeof Intl.supportedValuesOf === 'function' ? Intl.supportedValuesOf('timeZone') : ['UTC','Europe/London','America/New_York','America/Los_Angeles','Asia/Kolkata','Asia/Tokyo','Australia/Sydney'];
  return <><PageHead title="Workspace" eyebrow="Settings" description="A shared rhythm for your team’s work."/><Panel title="Workspace details"><Field label="Workspace name"><Input value={directory?.workspaceName ?? ''} readOnly/></Field><p className="muted">Your workspace content is encrypted and opened on approved devices.</p></Panel>
    <Panel title="Reporting timezone" description="Used for deadlines and progress reporting. Existing closing reports keep their original timezone."><LoadState loading={data.loading} error={data.error} retry={data.reload}><p>Current timezone: <strong>{data.value?.timezone ?? 'Not set'}</strong></p>{directory?.isOwner ? <Button variant="secondary" disabled={!data.value || !workspaceEditable(directory)} onClick={() => data.value && setReview({ pin: structuredClone(data.value.pin), before: data.value.timezone, after: data.value.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone })}>Change timezone</Button> : <p className="muted">An Owner can change the shared timezone.</p>}</LoadState></Panel>
    <Panel title="Appearance" description="Choose how the workspace looks on this device."><Field label="Colour theme"><Select value={theme} onChange={e => setTheme(e.target.value as typeof theme)}><option value="system">Use device setting</option><option value="light">Light</option><option value="dark">Dark</option></Select></Field></Panel>
    {review && <SecureConfirm open onClose={() => setReview(undefined)} title="Change reporting timezone?" description={`Change from ${review.before ?? 'not set'} to ${review.after}.`} confirmLabel="Save timezone" disabled={!review.after || review.after === review.before || !directory?.isOwner || !workspaceEditable(directory)} perform={async operationId => {
      const pending = await client.reporting.pending(); if (pending.includes(operationId)) return client.reporting.resume(operationId);
      return client.reporting.setTimezone(review.after, review.pin, operationId);
    }}><Field label="Timezone"><Select value={review.after} onChange={e => setReview({...review, after:e.target.value})}>{[...new Set(['UTC',review.after,...zones])].filter(Boolean).map(value => <option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</Select></Field></SecureConfirm>}</>;
}
export function DataSettings() {
  const { client, directory, reloadDirectory, navigate } = useApp(); const erasures = useSettingsLoad(() => client.lifecycle.erasures());
  const [choice, setChoice] = useState<'export'|'delete'|'cancel'|'erase'>(), [acknowledged, setAcknowledged] = useState(false), [name, setName] = useState('');
  const close = () => { setChoice(undefined); setAcknowledged(false); setName(''); };
  useEffect(() => client.auth.onClear(close), [client]);
  if (!directory) return null;
  const deletion = directory.deletion, deleting = directory.lifecycle === 'pending_deletion';
  return <><PageHead title="Data & privacy" description="Your workspace data, on your terms." eyebrow="Settings"/>
    {directory.isOwner && <Panel title="Export workspace" description="Download your readable workspace data and its history as a JSON file." actions={<Button variant="secondary" onClick={() => setChoice('export')}><Download size={16}/> Export workspace</Button>}><p className="muted">The file contains plaintext data. Store it privately. It is a data export, not a recovery kit or a backup you can restore.</p></Panel>}
    <Panel title="Profile erasure" description="Ask an Owner to remove your account from this workspace." actions={<Button variant="secondary" onClick={() => setChoice('erase')}>Request erasure</Button>}><p className="muted">Shared work and historical entries remain. Removing your account does not rewrite names already included in shared content.</p><LoadState loading={erasures.loading} error={erasures.error} retry={erasures.reload}>{erasures.value?.requests.length ? <div className="settings-list">{erasures.value.requests.map(request => <div className="settings-row" key={request.requestId}><div><strong>{directory.people.find(p => p.accountId === request.accountId)?.displayName ?? 'Former member'}</strong><p className="muted">Requested {dateLabel(request.requestedAt)}{request.needsSuccessor ? ' · Another Owner is needed first' : ''}</p></div><Badge tone={request.state === 'fulfilled' ? 'success' : 'warning'}>{request.state === 'fulfilled' ? 'Removed' : 'Requested'}</Badge>{directory.isOwner && request.state === 'requested' && <Button variant="ghost" onClick={() => navigate({ page:'settings',section:'people' })}>Review person</Button>}</div>)}</div> : <p className="muted">No erasure requests.</p>}</LoadState></Panel>
    {directory.isOwner && <Panel title={deleting ? 'Workspace deletion scheduled' : 'Delete workspace'} description={deleting ? 'Ordinary work is read-only until an Owner cancels, or the deletion deadline is reached.' : 'Permanently delete the entire workspace and revoke everyone’s access.'} actions={<Button variant={deleting ? 'secondary' : 'danger'} onClick={() => setChoice(deleting ? 'cancel' : 'delete')}>{deleting ? 'Cancel deletion' : <><Trash2 size={16}/> Delete workspace</>}</Button>}>{deleting && deletion ? <p>Deletion deadline: <strong>{dateLabel(deletion.deleteAfter)}</strong>. Any current Owner may cancel before then.</p> : <p className="muted">Deletion starts a seven-day waiting period. Any current Owner can cancel before the deadline. At the deadline, access ends and deletion cannot be reversed.</p>}<p className="muted">Live data is purged within 24 hours after the deadline; protected backups expire within 30 days after live purge. Downloaded exports cannot be recalled.</p></Panel>}
    {choice === 'export' && <SecureConfirm open onClose={close} title="Export workspace" description="This file will contain readable project data." confirmLabel="Download export" disabled={!acknowledged} perform={async () => {
      const download = await client.exports.generate({ acknowledgePlaintext: true });
      const url = URL.createObjectURL(new Blob([download.json], { type: download.mimeType }));
      const anchor = document.createElement('a'); anchor.href = url; anchor.download = download.filename; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
    }}><p>{client.exports.notice}</p><CheckOption checked={acknowledged} onChange={setAcknowledged}>I understand this file is not encrypted and will store it privately.</CheckOption></SecureConfirm>}
    {choice === 'delete' && <SecureConfirm open onClose={close} title="Delete this workspace?" description="Everyone will lose access at the end of the seven-day waiting period. Until then, the workspace will be read-only." confirmLabel="Schedule deletion" danger disabled={name !== directory.workspaceName} perform={operationId => client.lifecycle.requestDeletion(name, operationId)} onDone={reloadDirectory}><Field label={`Type ${directory.workspaceName} to confirm`}><Input autoComplete="off" value={name} onChange={e => setName(e.target.value)}/></Field></SecureConfirm>}
    {choice === 'cancel' && <SecureConfirm open onClose={close} title="Cancel workspace deletion?" description="Your workspace will remain available. Any separate access restrictions will still apply." confirmLabel="Keep workspace" perform={operationId => client.lifecycle.cancelDeletion(operationId)} onDone={reloadDirectory}/>}
    {choice === 'erase' && <SecureConfirm open onClose={close} title="Request profile erasure?" description="An Owner will review your request and remove your access. Shared work and history will remain." confirmLabel="Request erasure" perform={operationId => client.lifecycle.requestErasure(operationId)}/>}
  </>;
}
export function RestorePanel({ restoreId, onDone }: { restoreId: string; onDone?: () => void | Promise<void> }) {
  const { client, directory } = useApp(); const data = useSettingsLoad<ReadableRestoration>(() => client.restoration.inspect(restoreId), [restoreId]);
  const pending = useSettingsLoad(() => client.restoration.pending(), [restoreId]);
  const [review, setReview] = useState(false), [acknowledged, setAcknowledged] = useState(false), [resume, setResume] = useState<string>();
  const missing = data.value?.missingRecords.reduce<Record<string, number>>((all, record) => { all[record.kind] = (all[record.kind] ?? 0) + 1; return all; }, {}) ?? {};
  return <Panel title="Review recovered workspace" description="Verify what was recovered before reopening your workspace.">{pending.value?.map((id,index)=><div className="settings-row" key={id}><p>Recovery verification {pending.value!.length>1?index+1:''} has a saved attempt. It may already be complete.</p><Button variant="secondary" onClick={()=>setResume(id)}>Continue verification</Button></div>)}<LoadState loading={data.loading} error={data.error} retry={data.reload}>{data.value && <><p>Recovery point: <strong>{dateLabel(data.value.recoveredAt)}</strong></p><p>{data.value.verifiedSamples} content samples checked. Work after the recovery point may be missing.</p>{Object.keys(missing).length > 0 && <ul>{Object.entries(missing).map(([kind, count]) => <li key={kind}>{count} {kind==='project'?'projects':'items created after the recovery point'} could not be recovered</li>)}</ul>}<p className="muted">Current access removals and security changes still apply.</p><Button disabled={!!pending.value?.length} onClick={() => setReview(true)}>Review and reopen</Button></>}</LoadState>{review && <SecureConfirm open onClose={() => setReview(false)} title="Reopen the recovered workspace?" description={`Work after ${dateLabel(data.value?.recoveredAt)} may be missing. Other workspace restrictions will remain.`} confirmLabel="Verify and reopen" disabled={!acknowledged} perform={async operationId => {
    const pending = await client.restoration.pending(); if (pending.includes(operationId)) return client.restoration.resume(operationId);
    return client.restoration.verify(restoreId, true, operationId);
  }} {...(onDone ? {onDone} : {})}><CheckOption checked={acknowledged} onChange={setAcknowledged}>I have reviewed the recovery point and understand that later content may be missing.</CheckOption></SecureConfirm>}{resume&&<SecureConfirm open onClose={()=>setResume(undefined)} title="Continue recovery verification?" description="Check and finish the recovery review already saved on this browser." confirmLabel="Continue verification" perform={()=>client.restoration.resume(resume)} {...(onDone ? {onDone} : {})}/>}</Panel>;
}
export function MaintenanceSettings() {
  const { client, directory, reloadDirectory, reloadProjects } = useApp();
  // The verified directory records completion after the active update ID clears.
  // A fresh update context is only valid for the prior content format.
  const upToDate = directory?.writeSchema === currentContentSchema && !directory.activeUpgrade;
  const data = useSettingsLoad(() => directory?.isOwner && !upToDate ? client.upgrades.progress(directory.activeUpgrade?.migrationId) : Promise.resolve(null), [directory?.writeSchema, directory?.activeUpgrade?.migrationId]);
  const [action, setAction] = useState<'start'|'advance'|'finish'>();
  if (!directory?.isOwner) return <EmptyState title="Workspace updates are managed by Owners" description="An Owner will help if your workspace needs an update." icon={<ShieldCheck/>}/>;
  return <><PageHead title="Workspace updates" description="Keep encrypted workspace content compatible with the latest application." eyebrow="Settings"/><Panel title="Content update" description="Reads and security actions remain available while ordinary edits are paused." actions={<PasswordRefresh onDone={data.reload}/>}>
    {upToDate ? <><Badge tone="success">Up to date</Badge><p className="person-cell"><Check size={18}/> Your workspace is up to date.</p></> : <LoadState loading={data.loading} error={data.error} retry={data.reload}>{data.value && <>
    <Badge tone={data.value.state === 'completed' ? 'success' : data.value.state === 'paused' ? 'warning' : 'neutral'}>{data.value.state === 'available' ? 'Update available' : data.value.state === 'active' ? 'In progress' : data.value.state === 'completed' ? 'Up to date' : data.value.state === 'paused' ? 'Paused' : 'Stopped'}</Badge>
    {data.value.state === 'available' && <><p>{data.value.total} records are ready for this update. Ordinary editing will pause until it finishes.</p><Button onClick={() => setAction('start')}>Start update</Button></>}
    {data.value.state === 'active' && <><p>{data.value.completed} of {data.value.total} records updated.</p><progress max={Math.max(1,data.value.total)} value={data.value.completed} aria-label="Workspace update progress"/><p className="muted">You can return later or another Owner can continue.</p><Button onClick={() => setAction(data.value!.completed === data.value!.total ? 'finish' : 'advance')}><RefreshCw size={16}/>{data.value.completed === data.value.total ? 'Finish update' : 'Continue update'}</Button></>}
    {data.value.state === 'paused' && <p>The update will remain paused while workspace restrictions apply. Your completed progress is saved.</p>}
    {data.value.state === 'completed' && <p className="person-cell"><Check size={18}/> Your workspace is up to date.</p>}
  </>}</LoadState>}</Panel>{directory.activeRestore && <RestorePanel restoreId={directory.activeRestore.restoreId} onDone={reloadDirectory}/>}
    {action && data.value && <SecureConfirm open onClose={() => setAction(undefined)} title={action === 'start' ? 'Start workspace update?' : action === 'finish' ? 'Finish workspace update?' : 'Continue workspace update?'} description={action === 'start' ? 'Ordinary edits will pause. Your existing content and history are preserved.' : 'This device will verify and save the next part of the update.'} confirmLabel={action === 'start' ? 'Start update' : action === 'finish' ? 'Finish update' : 'Continue update'} perform={async operationId => {
      const pending = await client.upgrades.pending();
      const result = pending.includes(operationId) ? await client.upgrades.resume(operationId) : action === 'start' ? await client.upgrades.start(operationId) : action === 'finish' ? await client.upgrades.finish(data.value!.migrationId,operationId) : await client.upgrades.advance(data.value!.migrationId,operationId);
      return result;
    }} onDone={async () => { await reloadDirectory(); await reloadProjects(); }}/>}</>;
}
