'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Check, CheckCircle2, ShieldCheck } from 'lucide-react';
import type { EvidenceContext } from '../../src/shared/file-evidence.js';
import type { ReadableFileVersion } from '../../src/client/files-controller.js';
import { useApp } from '../shared/context';
import { Badge, Button, Field, Modal, Spinner, Textarea } from '../shared/ui';
import { type Project, workspaceWritable } from '../work/shared';
import { FileNotice, updatedLabel } from './common';

export function SharedSourceApproval({project,version,onChanged}:{project:Project;version:ReadableFileVersion;onChanged:()=>void|Promise<void>}){
 const {client,notify,directory}=useApp(),[context,setContext]=useState<EvidenceContext>(),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[confirmed,setConfirmed]=useState(false),[externalFile,setExternalFile]=useState<File>(),[pending,setPending]=useState<string[]>([]),[withdraw,setWithdraw]=useState(false),picker=useRef<HTMLInputElement>(null),projectId=project.graph.project.id,versionId=version.manifest.body.versionId,owner=project.authority.isOwner&&workspaceWritable(directory);
 const read=useCallback(async()=>{setLoading(true);setError(undefined);setConfirmed(false);setExternalFile(undefined);try{const value=await client.fileEvidence.context(projectId,{versionId}),attempts=await client.fileEvidence.pending();setContext(value);setPending(attempts.filter(r=>('approval'in r.payload&&r.payload.approval.body.reference.versionId===versionId)||('revocation'in r.payload&&r.payload.revocation.body.approvalId===value.approval?.body.approvalId)).map(r=>r.operationId));}catch(e){setError(e);}finally{setLoading(false);}},[client,projectId,versionId]);
 useEffect(()=>{void read();},[read]);
 async function choose(file:File|undefined){if(!file)return;setBusy(true);setError(undefined);try{const check=await client.files.verifyExternal(projectId,versionId,file);if(!check.matches)throw {code:'CHANGED_FILE'};setExternalFile(file);}catch(e){setError(e);}finally{setBusy(false);}}
 async function approve(){if(!pending.length&&!context){setError({code:'CONFLICT'});return;}setBusy(true);setError(undefined);try{if(pending.length){for(const id of pending)await client.fileEvidence.resume(id);}else await client.fileEvidence.approveShared(projectId,versionId,{reviewedContext:context!,...(externalFile?{externalFiles:{[versionId]:externalFile}}:{})});notify('This exact source version is approved.');await onChanged();await read();}catch(e){setError(e);const attempts=await client.fileEvidence.pending().catch(()=>[]);setPending(attempts.filter(r=>'approval'in r.payload&&r.payload.approval.body.reference.versionId===versionId).map(r=>r.operationId));}finally{setBusy(false);}}
 const approved=!!context?.approval&&!context.revocation,external=version.manifest.body.storage==='external';
 return <div className="stack"><div className="section-heading"><div><h3>Shared source approval</h3><p className="muted">An Owner can approve this exact source version for official delivery.</p></div><ShieldCheck size={23}/></div>{loading?<div className="files-loading"><Spinner/> Checking this version…</div>:<>{error!==undefined&&<FileNotice error={error} action={<Button variant="ghost" onClick={()=>void read()}>Check again</Button>}/>} {approved?<><Badge tone="success"><CheckCircle2 size={14}/> Approved exact v{version.manifest.body.version}</Badge><p className="muted">Approved {updatedLabel(context?.approval?.body.binding.issuedAt??null)}. Saving a newer version does not approve it.</p>{owner&&<Button variant="secondary" onClick={()=>setWithdraw(true)}>Withdraw approval</Button>}</>:context&&<><Badge tone={context.revocation?'warning':'neutral'}>{context.revocation?'Approval withdrawn':'Not yet approved'}</Badge><p className="muted">Task outputs are reviewed separately by the task’s reviewer.</p>{owner?<>{pending.length>0?<FileNotice warning>A saved approval attempt needs checking before you start another.</FileNotice>:<>{external&&<div className="file-verify"><Badge tone={externalFile?'success':'warning'}>{externalFile?<><Check size={13}/> Selected file matches</>:'Shared-drive file needs checking'}</Badge><Button variant="secondary" busy={busy} onClick={()=>picker.current?.click()}>Check selected file</Button><input className="sr-only" ref={picker} type="file" aria-label="Choose this shared source to check" onChange={e=>{void choose(e.target.files?.[0]);e.target.value='';}}/></div>}<label className="check-row"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/><span>I have reviewed this source version and approve it for delivery.</span></label></>}<Button busy={busy} disabled={!pending.length&&(!confirmed||external&&!externalFile)} onClick={()=>void approve()}>{pending.length?'Check saved approval':'Approve exact version'}</Button></>:<p className="muted">An Owner can review and approve this shared source.</p>}</>}</>}{withdraw&&<WithdrawApproval project={project} target={{versionId}} onClose={()=>setWithdraw(false)} onDone={async()=>{await onChanged();await read();}}/>}</div>;
}

export function WithdrawApproval({project,target,onClose,onDone}:{project:Project;target:{taskId?:string;versionId?:string};onClose:()=>void;onDone:()=>void|Promise<void>}){
 const {client,notify}=useApp(),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();
 async function save(){setBusy(true);setError(undefined);try{await client.fileEvidence.revoke(project.graph.project.id,target,reason.trim());notify('Approval withdrawn. A fresh review is needed before delivery.');await onDone();onClose();}catch(e){setError(e);}finally{setBusy(false);}}
 return <Modal open layout="form" title="Withdraw this approval?" description="The recorded versions and earlier history remain available." onClose={()=>{if(!busy)onClose();}} footer={<><Button variant="secondary" disabled={busy} onClick={onClose}>Keep approval</Button><Button variant="danger" busy={busy} disabled={!reason.trim()||!confirmed} onClick={()=>void save()}>Withdraw approval</Button></>}><div className="stack"><FileNotice warning>This work will need a fresh review before delivery. A delivery already copied to another location cannot be recalled.</FileNotice><Field label="Reason"><Textarea value={reason} maxLength={2000} disabled={busy} onChange={e=>setReason(e.target.value)} placeholder="Explain what needs to be checked again."/></Field><label className="check-row"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/><span>I understand that this approval will no longer allow new delivery.</span></label>{error!==undefined&&<FileNotice error={error}/>}</div></Modal>;
}
