'use client';
import { useState } from 'react';
import { Download } from 'lucide-react';
import { createFileArchive,FILE_ARCHIVE_NOTICE } from '../../src/client/files-archive.js';
import { useApp } from '../shared/context';
import { Badge,Button,EmptyState,Modal } from '../shared/ui';
import { projectName,type Project } from '../work/shared';
import { batchBytes,bytesLabel,FileIcon,FileNotice,useFiles } from './common';
export function ExportFiles({project,onClose}:{project:Project;onClose:()=>void}){
 const {client,notify}=useApp(),files=useFiles(project),[selected,setSelected]=useState<string[]>([]),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[progress,setProgress]=useState(''),size=files.entries.filter(e=>selected.includes(e.latestVersionId)&&e.version.manifest.body.storage==='managed').reduce((n,e)=>n+e.version.manifest.body.plainBytes,0);
 async function save(){setBusy(true);setError(undefined);try{const result=await createFileArchive(client.files,project.graph.project.id,selected,{onProgress:(done,total)=>setProgress('Preparing '+done+' of '+total+' files…')}),url=URL.createObjectURL(result.blob),a=document.createElement('a');a.href=url;a.download=(projectName(project).replace(/[^\p{L}\p{N} _-]/gu,'').slice(0,80)||'Maqbool')+'-files.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);notify('File package prepared. Keep it private.');onClose();}catch(e){setError(e);}finally{setBusy(false);}}
 return <Modal open layout="detail" title="Export files" description="Choose exact versions for a private download." onClose={()=>{if(!busy)onClose();}} footer={<><span className="file-footer-summary">{selected.length} selected · {bytesLabel(size)} uploaded contents</span><Button variant="secondary" disabled={busy} onClick={onClose}>Cancel</Button><Button busy={busy} disabled={!selected.length||!ack||size>batchBytes} onClick={()=>void save()}><Download size={15}/> Download selected files</Button></>}><div className="stack"><p className="muted">Choose up to 64 exact versions, with up to 250 MiB of uploaded file contents.</p>{files.entries.length?<div className="file-archive-list">{files.entries.map(e=><label className="file-archive-row" key={e.latestVersionId}><input type="checkbox" checked={selected.includes(e.latestVersionId)} disabled={busy||selected.length>=64&&!selected.includes(e.latestVersionId)} onChange={event=>{setSelected(old=>event.target.checked?[...old,e.latestVersionId]:old.filter(id=>id!==e.latestVersionId));setAck(false);}}/><FileIcon name={e.metadata.filename}/><span><strong>{e.metadata.filename}</strong><small className="muted">{e.metadata.documentReference} · Exact v{e.version.manifest.body.version} · {bytesLabel(e.version.manifest.body.plainBytes)}</small></span>{e.version.manifest.body.storage==='external'&&<Badge tone="warning">Reference only</Badge>}</label>)}</div>:!files.loading&&!files.error&&<EmptyState title="No files to export" description="Add project files before creating a file download."/>}{files.next&&<Button variant="secondary" busy={files.loading} disabled={busy} onClick={()=>void files.loadMore()}>Load more files</Button>}{size>batchBytes&&<FileNotice warning>The selected file contents exceed 250 MiB. Choose fewer files for this package.</FileNotice>}<p className="field-hint">The package contains readable files and a file list. Shared-drive files appear as references only; their contents are not included. Keep the package private.</p><label className="check-row"><input type="checkbox" checked={ack} disabled={busy} onChange={e=>setAck(e.target.checked)}/><span>I understand that this package contains readable files and will keep it private.</span></label>{progress&&<p className="muted" role="status">{progress}</p>}{error!==undefined&&<FileNotice error={error}/>} {files.error!==undefined&&<FileNotice error={files.error} action={<Button variant="ghost" onClick={()=>void files.reload()}>Try again</Button>}/>}</div></Modal>;
}
