'use client';
import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { AlertCircle, FileImage, FileSpreadsheet, FileText, Presentation, ShieldCheck } from 'lucide-react';
import type { ReadableFileEntry } from '../../src/client/files-controller.js';
import type { FileQuota } from '../../src/shared/files.js';
import { useApp } from '../shared/context';
import { Button, Spinner } from '../shared/ui';
import { customerError } from '../shared/errors';
import { editable, has, taskEditor, workspaceWritable, type Project } from '../work/shared';

export const uploadLimit=25*1024*1024,externalLimit=2*1024*1024*1024,batchLimit=64,batchBytes=250*1024*1024;
export const supported=['pdf','docx','xlsx','pptx','rtf','txt','csv','png','jpg','jpeg','webp'];
export const fileAccept=supported.map(v=>'.'+v).join(',');
export const externalWarning='Stored outside Maqbool. File contents are not included in cloud backups. Other people need access to this drive.';
export function bytesLabel(value:number){if(value<1024)return value+' B';const unit=value>=1024**3?'GiB':value>=1024**2?'MiB':'KiB',n=value/(unit==='GiB'?1024**3:unit==='MiB'?1024**2:1024);return new Intl.NumberFormat(undefined,{maximumFractionDigits:n>=10?0:1}).format(n)+' '+unit;}
export function updatedLabel(value:string|null){if(!value)return 'Not saved';const d=new Date(value);return Number.isNaN(+d)?'Not available':new Intl.DateTimeFormat(undefined,{day:'numeric',month:'short',year:'numeric'}).format(d);}
export function extension(name:string){return name.split('.').at(-1)?.toLowerCase()??'';}
export function FileIcon({name}:{name:string}){const ext=extension(name),Icon=['png','jpg','jpeg','webp'].includes(ext)?FileImage:['xlsx','csv'].includes(ext)?FileSpreadsheet:ext==='pptx'?Presentation:FileText;return <span className={'file-symbol file-symbol-'+(ext==='pdf'?'pdf':['xlsx','csv'].includes(ext)?'sheet':ext==='pptx'?'slides':'document')}><Icon size={20}/></span>;}
export function fileMessage(error:unknown){const code=error&&typeof error==='object'&&'code'in error?String(error.code):error instanceof Error?error.message:'',detail=error&&typeof error==='object'&&'serverCode'in error?String(error.serverCode):'',reason=detail||code;if(/TOO_LARGE/.test(reason))return 'This file is too large for this option. Upload files up to 25 MiB, or keep files up to 2 GiB on your shared drive.';if(/UNSUPPORTED_FORMAT/.test(reason))return 'Choose a PDF, Office document, RTF, text, CSV or supported image file.';if(/QUOTA|CAPACITY|STORAGE_FULL|INSUFFICIENT/.test(reason))return 'There is not enough storage for this upload. Keep the file on your shared drive, or review unfinished uploads.';if(/BUSY|UPLOAD_LIMIT/.test(reason))return 'Other files are being saved. Let them finish, then retry this file.';if(/CHANGED_FILE|INVALID_FILE/.test(reason))return 'This file could not be checked. Choose the expected file, or save the changed file as a new version.';return customerError(error);}
export function FileNotice({error,children,warning=false,action}:{error?:unknown;children?:ReactNode;warning?:boolean;action?:ReactNode}){return <div className={'notice '+(error?'notice-error':warning?'notice-warning':'')} role={error?'alert':'status'}>{error?<AlertCircle size={18}/>:<ShieldCheck size={18}/>}<span>{error?fileMessage(error):children}</span>{action}</div>;}
export function canManageFiles(project:Project){return project.authority.isOwner||has(project,'manage_tasks')||has(project,'plan_projects');}
export function canWriteFiles(project:Project,taskId?:string,kind:'source'|'output'='output'){const task=taskId?project.graph.tasks.find(t=>t.id===taskId):undefined;return editable(project,task?.phaseId)&&(!task||!['review','done','cancelled'].includes(task.state))&&(canManageFiles(project)||kind==='output'&&(task?taskEditor(project,task):has(project,'edit_assigned_tasks')&&project.graph.tasks.some(t=>t.assigneeIds.includes(project.authority.accountId)&&!['review','done','cancelled'].includes(t.state))));}
export function canWriteFileVersion(project:Project,entry:ReadableFileEntry){const affected=[...new Set([...entry.version.manifest.body.taskIds,...entry.links.filter(l=>l.mode==='latest').map(l=>l.taskId)])];return canWriteFiles(project,undefined,entry.kind)&&(canManageFiles(project)||entry.version.manifest.body.binding.accountId===project.authority.accountId)&&affected.every(id=>canWriteFiles(project,id,entry.kind));}
export function canDownloadFiles(project:Project){return project.authority.isOwner||has(project,'download_files');}
export function useFiles(project:Project,taskId?:string){
 const {client}=useApp(),[entries,setEntries]=useState<ReadableFileEntry[]>([]),[quota,setQuota]=useState<FileQuota>(),[loading,setLoading]=useState(true),[error,setError]=useState<unknown>(),[next,setNext]=useState<string|null>(null),epoch=useRef(0),alive=useRef(true);
 const read=useCallback(async(after?:string)=>{const stamp=++epoch.current;setLoading(true);setError(undefined);try{const page=await client.files.list(project.graph.project.id,{limit:100,...(taskId?{taskId}:{}),...(after?{after}:{})});if(alive.current&&stamp===epoch.current){setEntries(old=>after?[...old.filter(e=>!page.entries.some(p=>p.fileId===e.fileId)),...page.entries]:page.entries);setQuota(page.quota);setNext(page.nextCursor);}}catch(e){if(alive.current&&stamp===epoch.current)setError(e);}finally{if(alive.current&&stamp===epoch.current)setLoading(false);}},[client,project.graph.project.id,taskId]);
 useEffect(()=>{alive.current=true;void read();return()=>{alive.current=false;epoch.current++;};},[read]);
 return {entries,quota,loading,error,next,reload:()=>read(),loadMore:()=>next?read(next):Promise.resolve()};
}
export function FilesLoading(){return <div className="files-loading" role="status"><Spinner/><span>Opening project files…</span></div>;}
export function StorageMeter({quota,onManage}:{quota:FileQuota|undefined;onManage?:()=>void}){if(!quota)return null;const used=quota.usedBytes+quota.reservedBytes,percent=Math.min(100,used/quota.limitBytes*100);return <div className={'files-storage '+(used>=quota.limitBytes?'is-full':'')}><div><span><strong>{bytesLabel(used)}</strong> of {bytesLabel(quota.limitBytes)} used</span><span className="muted">{quota.reservedBytes>0?bytesLabel(quota.reservedBytes)+' reserved for unfinished uploads':'Includes retained versions'}</span></div><div className="files-storage-track" role="progressbar" aria-label="Workspace file storage" aria-valuenow={Math.round(percent)} aria-valuemin={0} aria-valuemax={100}><span style={{width:percent+'%'}}/></div>{onManage&&<Button variant="ghost" onClick={onManage}>View storage</Button>}</div>;}
export function saveDownload(bytes:Uint8Array,filename:string,mediaType='application/octet-stream'){const copy=new Uint8Array(bytes),url=URL.createObjectURL(new Blob([copy],{type:mediaType})),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
