'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import { AlertCircle,ArrowRight,Check,Download,Ellipsis,Folder,Link2,Package,Plus,RefreshCw,ShieldCheck,Trash2 } from 'lucide-react';
import type { CreateDeliveryItem,ReadableDelivery,ReadableDeliveryService } from '../../src/client/files-delivery-controller.js';
import type { StoredDeliveryOperation } from '../../src/client/files-delivery-store.js';
import type { ReadableFileVersion } from '../../src/client/files-controller.js';
import { localRelativePath } from '../../src/shared/local-files.js';
import { useApp } from '../shared/context';
import { Badge,Button,EmptyState,Field,Input,Modal,Select,Spinner,type BadgeTone } from '../shared/ui';
import { workspaceWritable,type Project } from '../work/shared';
import { bytesLabel,FileIcon,FileNotice,fileMessage,updatedLabel,useFiles } from './common';
import './delivery.css';

const labels={frozen:'Prepared',confirmed:'Ready to deliver',published:'Published & checked',cancelled:'Cancelled',superseded:'Replaced'};
const tones:Record<ReadableDelivery['state'],BadgeTone>={frozen:'info',confirmed:'purple',published:'success',cancelled:'neutral',superseded:'neutral'};
const operations={add:'Add',replace:'Replace',move:'Move',rename:'Rename',remove:'Remove'};
function DeliveryNotice({error}:{error:unknown}){const code=error&&typeof error==='object'&&'code'in error?String(error.code):'';
 const message=/DISK_FULL/.test(code)?'There is not enough free space in the shared folder. Free some space, then retry this delivery. Files already checked are kept.':
  /LOCAL_TIMEOUT/.test(code)?'The local file app took too long to respond. Check it is open, then retry. Your prepared delivery is kept.':
  /LOCAL_BUSY/.test(code)?'The local file app is busy. Let the current work finish, then retry.':
  /LOCAL_INTERRUPTED/.test(code)?'Publishing stopped before every file was checked. Reopen the local file app, then retry this same delivery to check and finish it.':
  /DELIVERY_TOO_LARGE|TOO_LARGE/.test(code)?'Choose up to 64 items with 250 MiB or less of uploaded files in one delivery. Shared-drive references do not count toward this size.':
  /DELIVERY_CHANGED|FILE_EVIDENCE_CHANGED|CONFLICT/.test(code)?'The files, approvals or folder have changed. Refresh this delivery before trying again.':
  /SERVICE_UNAVAILABLE|EDITOR_UNAVAILABLE/.test(code)?'This shared folder is not connected. Reconnect your local file app, or download the package.':
  /TRANSPORT/.test(code)?'The connection stopped. Check your local file app is open and this browser can reach it. Your prepared delivery is kept.':fileMessage(error);
 return <div className="notice notice-error" role="alert"><AlertCircle size={18}/><span>{message}</span></div>;
}
function CompanionLinks(){return <div className="delivery-companion-links"><a href="/downloads/maqbool-local-mac.zip" download>Get the Mac companion</a><a href="/local-files-help.html" target="_blank" rel="noopener noreferrer">Setup guide</a></div>;}
function downloadBlob(blob:Blob,filename:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}

export function ProjectDelivery({project}:{project:Project}){
 const {client,navigate,notify,directory}=useApp(),projectId=project.graph.project.id,[rows,setRows]=useState<ReadableDelivery[]>([]),[services,setServices]=useState<ReadableDeliveryService[]>([]),[pending,setPending]=useState<StoredDeliveryOperation[]>([]),[next,setNext]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<unknown>(),[selected,setSelected]=useState<ReadableDelivery>(),[dialog,setDialog]=useState<'create'|'local'|null>(null),[supersedes,setSupersedes]=useState<ReadableDelivery>(),[resumeBusy,setResumeBusy]=useState(''),epoch=useRef(0),alive=useRef(true);
 const owner=project.authority.isOwner,writable=workspaceWritable(directory),[more,setMore]=useState(false),menu=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!more)return;const close=(event:PointerEvent)=>{if(menu.current&&!menu.current.contains(event.target as Node))setMore(false);};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);},[more]);
 const load=useCallback(async(after?:string)=>{if(!owner){setLoading(false);return;}const stamp=++epoch.current;setLoading(true);setError(undefined);
  const [page,connections,drafts]=await Promise.allSettled([client.deliveries.list(projectId,after),client.deliveries.services(projectId),client.deliveries.pending()]);
  if(!alive.current||stamp!==epoch.current)return;
  if(page.status==='fulfilled'){setRows(old=>after?[...old.filter(r=>!page.value.entries.some(p=>p.batch.body.batchId===r.batch.body.batchId)),...page.value.entries]:page.value.entries);setNext(page.value.nextCursor);}else setError(page.reason);
  if(connections.status==='fulfilled')setServices(connections.value);else if(page.status==='fulfilled')setError(connections.reason);
  if(drafts.status==='fulfilled')setPending(drafts.value.filter(r=>('batch'in r.payload?r.payload.batch.body.binding:'approval'in r.payload?r.payload.approval.body.binding:r.payload.mutation.body.binding).projectId===projectId));
  setLoading(false);
 },[client,projectId,owner]);
 useEffect(()=>{alive.current=true;void load();return()=>{alive.current=false;epoch.current++;};},[load]);
 async function resume(operationId:string){setResumeBusy(operationId);setError(undefined);try{await client.deliveries.resume(operationId);notify('Saved attempt checked.','success');await load();}catch(e){setError(e);}finally{setResumeBusy('');}}
 async function discard(operationId:string){setResumeBusy(operationId);setError(undefined);try{await client.deliveries.discard(operationId);notify('This local attempt was removed. Any saved delivery remains available.','info');await load();}catch(e){setError(e);}finally{setResumeBusy('');}}
 async function openCreated(batchId:string){setDialog(null);setSupersedes(undefined);await load();try{setSelected(await client.deliveries.read(projectId,batchId));}catch(e){setError(e);}}
 if(!owner)return <EmptyState title="Delivery is managed by Owners" description="Ask an Owner to prepare and deliver the approved files for this project." icon={<Package/>} action={<Button variant="secondary" onClick={()=>navigate({page:'project',projectId,tab:'files'})}>Back to files</Button>}/>;
 return <div className="delivery-page stack"><header className="delivery-heading"><div><h2>Delivery</h2><p>Prepare approved files for handover.</p></div><div className="button-row"><div className="delivery-more-control" ref={menu}><Button variant="ghost" aria-haspopup="menu" aria-expanded={more} aria-label="More delivery options" onClick={()=>setMore(!more)} onKeyDown={e=>{if(e.key==='Escape')setMore(false);}}><Ellipsis size={20}/></Button>{more&&<div className="delivery-menu" role="menu"><button type="button" role="menuitem" onClick={()=>{setMore(false);setDialog('local');}}><Link2 size={16}/> Shared folders</button></div>}</div><Button disabled={!writable} onClick={()=>{setSupersedes(undefined);setDialog('create');}}><Plus size={16}/> New delivery</Button></div></header>
  {error!==undefined&&<DeliveryNotice error={error}/>}
  {pending.length>0&&<section className="delivery-attempts"><div><strong>A delivery attempt needs checking</strong><p>Your prepared details are kept until the result is clear.</p></div>{pending.map(attempt=><div className="delivery-attempt" key={attempt.operationId}><span>{attempt.action==='create'?'Prepare delivery':attempt.action==='publish'?'Publish to folder':attempt.action==='pair'?'Connect shared folder':attempt.action==='confirm'?'Confirm delivery':attempt.action==='record_package'?'Prepare package':attempt.action==='revoke_service'?'Disconnect shared folder':'Cancel delivery'}</span><Button variant="secondary" busy={resumeBusy===attempt.operationId} disabled={!!resumeBusy} onClick={()=>void resume(attempt.operationId)}>Check saved attempt</Button><Button variant="ghost" disabled={!!resumeBusy} onClick={()=>void discard(attempt.operationId)}>Remove local attempt</Button></div>)}</section>}
  <div className="delivery-list-heading"><h3>Your deliveries</h3><Button variant="ghost" busy={loading} onClick={()=>void load()}><RefreshCw size={15}/> Refresh</Button></div>
  {loading&&!rows.length?<div className="files-loading" role="status"><Spinner/> Opening deliveries…</div>:rows.length?<div className="delivery-table-card table-wrap"><table className="table delivery-table"><thead><tr><th scope="col">Delivery</th><th scope="col">Files</th><th scope="col">Destination</th><th scope="col">Status</th><th scope="col">Prepared</th><th scope="col"><span className="sr-only">Review delivery</span></th></tr></thead><tbody>{rows.map(row=><tr key={row.batch.body.batchId}><td><button className="delivery-name" onClick={()=>setSelected(row)}><span className="delivery-symbol"><Package size={21}/></span><span><strong>{row.details.label}</strong><small>{row.packageDownloads>0?'Package prepared · '+row.packageDownloads+(row.packageDownloads===1?' time':' times'):'Exact versions are kept for this delivery'}</small></span></button></td><td>{row.batch.body.items.length} {row.batch.body.items.length===1?'item':'items'}</td><td><span className="delivery-destination"><Folder size={14}/>{row.details.rootLabel}</span></td><td><Badge tone={tones[row.state]}>{labels[row.state]}</Badge></td><td className="muted">{updatedLabel(row.createdAt)}</td><td><Button variant="ghost" aria-label={'Review '+row.details.label} onClick={()=>setSelected(row)}><ArrowRight size={17}/></Button></td></tr>)}</tbody></table></div>:!error&&<div className="delivery-table-card"><EmptyState title="Ready when your files are" description="Prepare the approved versions for a clear, checked handover." icon={<Package/>} action={<div className="button-row"><Button disabled={!writable} onClick={()=>setDialog('create')}>Prepare a delivery</Button><Button variant="secondary" onClick={()=>navigate({page:'project',projectId,tab:'files'})}>View project files</Button></div>}/></div>}
  {next&&<div className="delivery-more"><Button variant="secondary" busy={loading} onClick={()=>void load(next)}>Load more deliveries</Button></div>}
  <p className="delivery-access-note">Downloading a package does not mark files as published. A connected folder confirms the written files before a delivery is marked complete.</p>
  {dialog==='create'&&<CreateDelivery project={project} services={services.filter(s=>s.state==='active')} {...(supersedes?{supersedes}:{})} onClose={()=>{setDialog(null);setSupersedes(undefined);}} onCreated={openCreated}/>}
  {dialog==='local'&&<LocalFolders projectId={projectId} services={services} onClose={()=>setDialog(null)} onChanged={load}/>}
  {selected&&<DeliveryDetail project={project} initial={selected} services={services.filter(s=>s.state==='active')} onClose={()=>setSelected(undefined)} onChanged={load} onLocal={()=>{setSelected(undefined);setDialog('local');}} onSupersede={row=>{setSelected(undefined);setSupersedes(row);setDialog('create');}}/>}
 </div>;
}

type DraftRow={id:string;item:CreateDeliveryItem;filename:string;version:string;location:'managed'|'external';size:number;reference:string};
function CreateDelivery({project,services,supersedes,onClose,onCreated}:{project:Project;services:ReadableDeliveryService[];supersedes?:ReadableDelivery;onClose:()=>void;onCreated:(batchId:string)=>Promise<void>}){
 const {client,navigate}=useApp(),files=useFiles(project),projectId=project.graph.project.id,[label,setLabel]=useState(supersedes?supersedes.details.label+' · updated':''),[rootLabel,setRootLabel]=useState(supersedes?.details.rootLabel??services[0]?.metadata.rootLabel??'Delivery'),[rows,setRows]=useState<DraftRow[]>(supersedes?supersedes.batch.body.items.map((item,index)=>({id:crypto.randomUUID(),item:{operation:item.operation,versionId:item.versionId,approvalId:item.approvalId,destination:supersedes.details.items[index]!.destination,...(supersedes.details.items[index]!.fromPath?{fromPath:supersedes.details.items[index]!.fromPath}:{}),expectedOldSha256:supersedes.details.items[index]!.expectedOldSha256},filename:supersedes.details.items[index]!.filename,version:'',location:supersedes.details.items[index]!.externalPath?'external':'managed',size:supersedes.details.items[index]!.plainBytes,reference:''})):[]),[fileId,setFileId]=useState(''),[versions,setVersions]=useState<ReadableFileVersion[]>([]),[versionId,setVersionId]=useState(''),[versionCursor,setVersionCursor]=useState<string|null>(null),[operation,setOperation]=useState<CreateDeliveryItem['operation']>('add'),[destination,setDestination]=useState(''),[fromPath,setFromPath]=useState(''),[existing,setExisting]=useState<{name:string;hash:string}>(),[checking,setChecking]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[notice,setNotice]=useState(''),picker=useRef<HTMLInputElement>(null),stamp=useRef(0),alive=useRef(true);
 useEffect(()=>()=>{alive.current=false;stamp.current++;},[]);
 const selected=versions.find(v=>v.manifest.body.versionId===versionId),managedBytes=rows.reduce((sum,row)=>sum+(row.location==='managed'&&row.item.operation!=='remove'?row.size:0),0);
 async function chooseFile(id:string,after?:string){const version=++stamp.current;setChecking(true);setError(undefined);if(!after){setFileId(id);setVersions([]);setVersionId('');setExisting(undefined);}
  try{if(!id)return;const page=await client.files.versions(projectId,id,after);if(!alive.current||version!==stamp.current)return;const ready=page.versions.filter(v=>v.state==='ready');setVersions(old=>after?[...old,...ready]:ready);setVersionCursor(page.nextVersion);
   if(!after){const value=ready.at(-1);setVersionId(value?.manifest.body.versionId??'');setDestination(value?.metadata.filename??'');}}
  catch(e){if(alive.current&&version===stamp.current)setError(e);}finally{if(alive.current&&version===stamp.current)setChecking(false);}
 }
 async function checkExisting(file:File|undefined){if(!file)return;setChecking(true);setError(undefined);setExisting(undefined);try{const hash=await client.auth.worker.hashFile(file);if(alive.current)setExisting({name:file.name,hash});}catch(e){if(alive.current)setError(e);}finally{if(alive.current)setChecking(false);}}
 async function add(){setError(undefined);setNotice('');if(!selected){setNotice('Choose a file and an exact version.');return;}if(rows.length>=64){setNotice('A delivery can include up to 64 items.');return;}
  if(!localRelativePath.safeParse(destination).success||(['move','rename'].includes(operation)&&!localRelativePath.safeParse(fromPath).success)){setNotice('Use a file name or a folder/name within the destination folder. Avoid absolute paths, backslashes and “..”.');return;}
  if(operation!=='add'&&!existing){setNotice('Choose the existing file so its current contents can be checked.');return;}
  if(['move','rename','remove'].includes(operation)&&existing?.hash!==selected.metadata.sha256){setNotice('The existing file differs from this approved version. Choose the matching file, or have the changed version reviewed first.');return;}
  setChecking(true);try{const evidence=await client.fileEvidence.context(projectId,{versionId});if(!alive.current)return;
   if(!evidence.approval||evidence.revocation){setNotice('This exact version needs approval before delivery. Open it in Project files to review it.');return;}
   if(evidence.approval.body.purpose==='ukda.file-review.v1'){const taskId=evidence.approval.body.taskId,task=project.graph.tasks.find(t=>t.id===taskId);if(!task||task.state!=='done'){setNotice('The related task must be approved and done before this version can be delivered.');return;}}
   const item:CreateDeliveryItem={operation,versionId,approvalId:evidence.approval.body.approvalId,destination:destination.trim(),...(['move','rename'].includes(operation)?{fromPath:fromPath.trim()}:{}),expectedOldSha256:operation==='add'?null:existing!.hash};
   const paths=[item.destination,...(item.fromPath?[item.fromPath]:[])];if(paths.some(path=>rows.some(row=>[row.item.destination,row.item.fromPath].filter(Boolean).some(other=>other===path||path.startsWith(other+'/')||other!.startsWith(path+'/'))))||item.fromPath===item.destination){setNotice('Each destination and source location must be used only once in this delivery.');return;}
   const size=selected.manifest.body.plainBytes;if(managedBytes+(selected.manifest.body.storage==='managed'&&operation!=='remove'?size:0)>250*1024*1024){setNotice('Uploaded files in one delivery must total 250 MiB or less. Prepare a smaller delivery.');return;}
   setRows(old=>[...old,{id:crypto.randomUUID(),item,filename:selected.metadata.filename,version:selected.manifest.body.version,location:selected.manifest.body.storage,size,reference:selected.metadata.documentReference}]);setFileId('');setVersions([]);setVersionId('');setDestination('');setFromPath('');setExisting(undefined);setOperation('add');
  }catch(e){if(alive.current)setError(e);}finally{if(alive.current)setChecking(false);}
 }
 async function save(){if(!label.trim()||!rootLabel.trim()||!rows.length){setNotice('Name the delivery, choose its destination folder and add at least one approved version.');return;}setBusy(true);setError(undefined);try{const result=await client.deliveries.create({projectId,label:label.trim(),rootLabel:rootLabel.trim(),items:rows.map(r=>r.item),...(supersedes?{supersedes:supersedes.batch.body.batchId}:{})});if(result.batchId)await onCreated(result.batchId);}catch(e){if(alive.current)setError(e);}finally{if(alive.current)setBusy(false);}}
 return <Modal open layout="detail" title={supersedes?'Prepare an updated delivery':'Prepare a delivery'} description="Choose approved versions and where each file belongs." onClose={()=>{if(!busy&&!checking)onClose();}} footer={<><span className="file-footer-summary">{rows.length} {rows.length===1?'item':'items'} · {bytesLabel(managedBytes)} of uploaded files</span><Button variant="secondary" disabled={busy||checking} onClick={onClose}>Cancel</Button><Button busy={busy} disabled={checking||!rows.length} onClick={()=>void save()}>Prepare for review <ArrowRight size={16}/></Button></>}>
  <div className="delivery-form stack"><div className="form-row"><Field label="Delivery name"><Input value={label} maxLength={160} onChange={e=>setLabel(e.target.value)} disabled={busy} placeholder="For example, October handover"/></Field><Field label="Destination folder" hint="The name of the folder chosen in your local file app, or for your downloaded package."><Input value={rootLabel} maxLength={160} disabled={busy} onChange={e=>setRootLabel(e.target.value)}/>{services.length>0&&<Select aria-label="Use a connected destination folder" value="" disabled={busy} onChange={e=>{const service=services.find(s=>s.serviceId===e.target.value);if(service)setRootLabel(service.metadata.rootLabel);}}><option value="">Use a connected folder…</option>{services.map(s=><option key={s.serviceId} value={s.serviceId}>{s.metadata.label} · {s.metadata.rootLabel}</option>)}</Select>}</Field></div>
   {supersedes&&<FileNotice>The previous delivery stays in your history and will be marked replaced when this one is prepared.</FileNotice>}
   <section className="delivery-add-item stack"><h3>Add an approved version</h3><div className="form-row"><Field label="Project file"><Select value={fileId} disabled={checking||busy} onChange={e=>void chooseFile(e.target.value)}><option value="">Choose a file…</option>{files.entries.map(file=><option key={file.fileId} value={file.fileId}>{file.metadata.documentReference} · {file.metadata.filename}</option>)}</Select></Field><Field label="Exact version"><Select value={versionId} disabled={!fileId||checking||busy} onChange={e=>{setVersionId(e.target.value);setExisting(undefined);const v=versions.find(v=>v.manifest.body.versionId===e.target.value);if(v)setDestination(v.metadata.filename);}}><option value="">Choose a version…</option>{versions.map(v=><option key={v.manifest.body.versionId} value={v.manifest.body.versionId}>v{v.manifest.body.version} · {updatedLabel(v.completedAt)}</option>)}</Select></Field></div>
    {(files.next||versionCursor)&&<div className="button-row">{files.next&&<Button variant="ghost" busy={files.loading} onClick={()=>void files.loadMore()}>Load more project files</Button>}{versionCursor&&<Button variant="ghost" busy={checking} onClick={()=>void chooseFile(fileId,versionCursor)}>Load more versions</Button>}</div>}
    {files.error!==undefined&&<FileNotice error={files.error} action={<Button variant="ghost" onClick={()=>void files.reload()}>Try again</Button>}/>}
    <div className="form-row"><Field label="Action"><Select value={operation} disabled={busy||checking} onChange={e=>{setOperation(e.target.value as CreateDeliveryItem['operation']);setExisting(undefined);}}>{Object.entries(operations).map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select></Field><Field label={operation==='remove'?'Existing location':'Destination'} hint="A file name or folder/name within the chosen folder."><Input value={destination} maxLength={1024} disabled={busy||checking} onChange={e=>setDestination(e.target.value)} placeholder="For example, Approved/document.pdf"/></Field></div>
    {['move','rename'].includes(operation)&&<Field label="Current location" hint="Where the matching file is now, within the chosen folder."><Input value={fromPath} maxLength={1024} disabled={busy||checking} onChange={e=>setFromPath(e.target.value)} placeholder="Drafts/document.pdf"/></Field>}
    {operation!=='add'&&<div className="delivery-existing-check"><input className="sr-only" ref={picker} type="file" aria-label="Choose the existing file to check" disabled={busy||checking} onChange={e=>{void checkExisting(e.target.files?.[0]);e.target.value='';}}/><div><strong>{existing?'Existing file checked':'Check the existing file'}</strong><p>{existing?existing.name:'Choose the file from the destination folder. Its contents stay on this device.'}</p></div><Button variant="secondary" busy={checking} disabled={busy} onClick={()=>picker.current?.click()}>{existing?'Choose another file':'Choose existing file'}</Button></div>}
    {selected?.manifest.body.storage==='external'&&<FileNotice warning>This file stays on your shared drive. A downloaded package contains its reference; publishing requires access to the matching file in the connected folder.</FileNotice>}
    <div className="delivery-add-footer"><Button variant="ghost" onClick={()=>navigate({page:'project',projectId,tab:'files'})}>Review project files</Button><Button variant="secondary" busy={checking} disabled={busy||!selected} onClick={()=>void add()}><Plus size={15}/> Add to delivery</Button></div>
   </section>
   {notice&&<FileNotice warning>{notice}</FileNotice>}{error!==undefined&&<DeliveryNotice error={error}/>}
   {rows.length>0&&<div className="delivery-items">{rows.map(row=><article className="delivery-draft-item" key={row.id}><FileIcon name={row.filename}/><div><strong>{row.filename}</strong><small>{row.reference}{row.version?' · v'+row.version:''} · {row.location==='external'?'Shared drive':bytesLabel(row.size)}</small><span>{row.item.fromPath?row.item.fromPath+' → ':''}{row.item.destination}</span></div><Badge tone={row.item.operation==='remove'?'danger':row.item.operation==='replace'?'warning':'neutral'}>{operations[row.item.operation]}</Badge><Button variant="ghost" disabled={busy} aria-label={'Remove '+row.filename+' from delivery'} onClick={()=>setRows(old=>old.filter(r=>r.id!==row.id))}><Trash2 size={16}/></Button></article>)}</div>}
  </div>
 </Modal>;
}

function DeliveryDetail({project,initial,services,onClose,onChanged,onLocal,onSupersede}:{project:Project;initial:ReadableDelivery;services:ReadableDeliveryService[];onClose:()=>void;onChanged:()=>Promise<void>;onLocal:()=>void;onSupersede:(row:ReadableDelivery)=>void}){
 const {client,notify,directory}=useApp(),projectId=project.graph.project.id,batchId=initial.batch.body.batchId,[row,setRow]=useState(initial),[busy,setBusy]=useState(''),[error,setError]=useState<unknown>(),[confirmed,setConfirmed]=useState(false),[cancelConfirm,setCancelConfirm]=useState(false),[progress,setProgress]=useState({completed:0,total:initial.batch.body.items.length}),[serviceId,setServiceId]=useState(services.find(s=>s.metadata.rootLabel===initial.details.rootLabel)?.serviceId??''),alive=useRef(true),writable=workspaceWritable(directory);
 useEffect(()=>()=>{alive.current=false;},[]);
 async function refresh(){setRow(await client.deliveries.read(projectId,batchId));await onChanged();}
 async function action(value:'confirm'|'cancel'|'package'|'publish'|'refresh'){if(busy)return;setBusy(value);setError(undefined);setProgress({completed:0,total:row.batch.body.items.length});try{
   if(value==='confirm'){await client.deliveries.confirm(projectId,batchId);notify('Delivery confirmed.','success');}
   else if(value==='cancel'){await client.deliveries.cancel(projectId,batchId);setCancelConfirm(false);notify('Delivery cancelled.','info');}
   else if(value==='package'){const result=await client.deliveries.downloadPackage(projectId,batchId,(completed,total)=>{if(alive.current)setProgress({completed,total});});downloadBlob(result.blob,result.filename);notify('Your package is ready. This does not mark it as published.','success');}
   else if(value==='publish'){await client.deliveries.publishLocal(projectId,batchId,serviceId,(completed,total)=>{if(alive.current)setProgress({completed,total});});notify('Files published and checked in the shared folder.','success');}
   await refresh();
  }catch(e){if(alive.current)setError(e);}finally{if(alive.current)setBusy('');}}
 const ready=row.state==='confirmed',editable=['frozen','confirmed'].includes(row.state),selectedService=services.find(s=>s.serviceId===serviceId),connected=!!selectedService&&client.deliveries.isLocalConnected(projectId,serviceId);
 return <Modal open layout="detail" title={row.state==='frozen'?'Review this delivery':row.details.label} description={row.details.rootLabel+' · '+row.batch.body.items.length+' exact '+(row.batch.body.items.length===1?'version':'versions')} onClose={()=>{if(!busy)onClose();}} footer={<><span className="file-footer-summary"><Badge tone={tones[row.state]}>{labels[row.state]}</Badge></span><Button variant="secondary" disabled={!!busy} onClick={onClose}>Close</Button>{row.state==='frozen'&&<Button busy={busy==='confirm'} disabled={!confirmed||!writable||!!busy} onClick={()=>void action('confirm')}><ShieldCheck size={16}/> Confirm delivery</Button>}{ready&&<Button variant="secondary" busy={busy==='package'} disabled={!!busy||!writable} onClick={()=>void action('package')}><Download size={16}/> Download package</Button>}{ready&&connected&&<Button busy={busy==='publish'} disabled={!!busy||!writable} onClick={()=>void action('publish')}><Folder size={16}/> Publish to shared folder</Button>}</>}>
  <div className="delivery-detail stack"><div className="delivery-detail-summary"><span><Package size={17}/>{row.batch.body.items.length} items</span><span><Folder size={17}/>{row.details.rootLabel}</span>{row.state==='published'&&<span><Check size={17}/> Written files checked</span>}</div>
   {row.state==='frozen'&&<FileNotice>Check the exact versions and destinations below. Preparing this delivery has not changed any files in your shared folder.</FileNotice>}
   <div className="table-wrap delivery-review-table"><table className="table"><thead><tr><th scope="col">File</th><th scope="col">Version</th><th scope="col">Action</th><th scope="col">Destination</th><th scope="col">Location</th></tr></thead><tbody>{row.batch.body.items.map((item,index)=>{const detail=row.details.items[index]!;return <tr key={index}><td><div className="delivery-review-name"><FileIcon name={detail.filename}/><span><strong>{detail.filename}</strong><small>{row.versions[index]?.documentReference} · {bytesLabel(detail.plainBytes)}</small></span></div></td><td><span className="file-version-label">v{row.versions[index]?.version}</span></td><td><Badge tone={item.operation==='remove'?'danger':item.operation==='replace'?'warning':'neutral'}>{operations[item.operation]}</Badge></td><td><div className="delivery-review-path">{detail.fromPath&&<small>From {detail.fromPath}</small>}<span>{detail.destination}</span></div></td><td><Badge tone={detail.externalPath?'warning':'neutral'}>{detail.externalPath?'Shared drive':'Uploaded'}</Badge></td></tr>;})}</tbody></table></div>
   {row.state==='frozen'&&<label className="delivery-confirm"><input type="checkbox" checked={confirmed} disabled={!!busy} onChange={e=>setConfirmed(e.target.checked)}/><span>I have checked these versions and destinations.</span></label>}
   {ready&&<><section className="delivery-publish-choice stack"><h3>Choose how to deliver</h3><p>A package gives you the uploaded files and a list of shared-drive references. Connected publishing places and checks the files in your organisation’s chosen folder.</p>{services.filter(s=>s.metadata.rootLabel===row.details.rootLabel).length>0&&<Field label="Connected folder"><Select value={serviceId} disabled={!!busy} onChange={e=>setServiceId(e.target.value)}><option value="">Choose a connected folder…</option>{services.filter(s=>s.metadata.rootLabel===row.details.rootLabel).map(s=><option key={s.serviceId} value={s.serviceId}>{s.metadata.label} · {s.metadata.rootLabel}</option>)}</Select></Field>}{!connected&&<div className="delivery-connect-fallback"><span>{selectedService?'Reconnect this folder on your browser before publishing.':'Connect your local file app to publish to this folder.'}</span><Button variant="secondary" disabled={!!busy} onClick={onLocal}><Link2 size={16}/> Connect shared folder</Button></div>}{!connected&&<CompanionLinks/>}<FileNotice warning>Downloaded files can be read outside Maqbool. Keep the package somewhere safe. Shared-drive files are included as references.</FileNotice></section></>}
   {row.state==='published'&&<div className="delivery-success"><ShieldCheck size={23}/><div><strong>Published and checked</strong><p>The connected folder verified the delivered files. This delivery is complete.</p></div></div>}
   {['cancelled','superseded'].includes(row.state)&&<FileNotice>{row.state==='cancelled'?'This delivery was cancelled. Its details remain available for reference.':'A newer delivery replaced this one. Its original details remain available for reference.'}</FileNotice>}
   {['package','publish'].includes(busy)&&<div className="delivery-progress" role="status"><Spinner/><span>{busy==='package'?'Preparing your package':'Publishing and checking files'} · {progress.completed} of {progress.total}</span><div className="files-storage-track"><span style={{width:(progress.total?progress.completed/progress.total*100:0)+'%'}}/></div></div>}
   {error!==undefined&&<DeliveryNotice error={error}/>}<div className="delivery-detail-actions"><Button variant="ghost" busy={busy==='refresh'} disabled={!!busy} onClick={()=>void action('refresh')}>Refresh delivery</Button>{editable&&<><Button variant="ghost" disabled={!!busy||!writable} onClick={()=>onSupersede(row)}>Prepare an updated delivery</Button><Button variant="ghost" disabled={!!busy||!writable} onClick={()=>setCancelConfirm(!cancelConfirm)}>Cancel delivery</Button></>}</div>
   {cancelConfirm&&<div className="delivery-cancel"><span>Cancel this delivery? Files already downloaded or placed in a folder are kept.</span><Button variant="secondary" disabled={!!busy} onClick={()=>setCancelConfirm(false)}>Keep delivery</Button><Button variant="danger" busy={busy==='cancel'} disabled={!!busy} onClick={()=>void action('cancel')}>Cancel delivery</Button></div>}
  </div>
 </Modal>;
}

function LocalFolders({projectId,services,onClose,onChanged}:{projectId:string;services:ReadableDeliveryService[];onClose:()=>void;onChanged:()=>Promise<void>}){
 const {client,notify}=useApp(),[address,setAddress]=useState('https://localhost:3411'),[label,setLabel]=useState('This computer'),[code,setCode]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState<unknown>(),[notice,setNotice]=useState(''),[revoke,setRevoke]=useState(''),alive=useRef(true);
 useEffect(()=>()=>{alive.current=false;},[]);
 async function connect(){setBusy('connect');setError(undefined);setNotice('');try{const result=await client.deliveries.connectLocal(projectId,{address:address.trim(),label:label.trim(),code:code.trim()});setCode('');setNotice('Connected to '+result.rootLabel+'.');notify('Shared folder connected on this browser.','success');await onChanged();}catch(e){if(alive.current)setError(e);}finally{if(alive.current)setBusy('');}}
 async function check(service:ReadableDeliveryService){setBusy(service.serviceId);setError(undefined);try{const status=await client.deliveries.localStatus(service.metadata.address);if(status.serviceId!==service.serviceId||status.publicKey!==service.publicKey)throw new Error('The connected folder changed.');setNotice(service.metadata.label+' is available. '+(client.deliveries.isLocalConnected(projectId,service.serviceId)?'Ready to publish.':'Enter its current connection code to reconnect on this browser.'));}catch(e){if(alive.current)setError(e);}finally{if(alive.current)setBusy('');}}
 async function revokeService(service:ReadableDeliveryService){setBusy(service.serviceId);setError(undefined);try{await client.deliveries.revokeService(projectId,service.serviceId);client.deliveries.disconnectLocal(projectId,service.serviceId);setRevoke('');notify('Shared folder access removed.','success');await onChanged();}catch(e){if(alive.current)setError(e);}finally{if(alive.current)setBusy('');}}
 return <Modal open layout="form" title="Shared-folder publishing" description="Connect your organisation’s file app to place approved files in a folder you control." onClose={()=>{if(!busy)onClose();}} footer={<Button variant="secondary" disabled={!!busy} onClick={onClose}>Done</Button>}>
  <div className="delivery-local stack"><FileNotice>Publishing works while the local file app is open. You can always download a delivery package when it is unavailable.</FileNotice>{services.filter(s=>s.state==='active').map(service=><article className="delivery-local-card" key={service.serviceId}><div className="delivery-local-card-head"><Folder size={22}/><div><strong>{service.metadata.label}</strong><p>{service.metadata.rootLabel}</p></div><Badge tone={client.deliveries.isLocalConnected(projectId,service.serviceId)?'success':'neutral'}>{client.deliveries.isLocalConnected(projectId,service.serviceId)?'Connected':'Reconnect'}</Badge></div><div className="button-row"><Button variant="secondary" busy={busy===service.serviceId} disabled={!!busy} onClick={()=>void check(service)}>Check connection</Button><Button variant="ghost" disabled={!!busy} onClick={()=>{setAddress(service.metadata.address);setLabel(service.metadata.label);setNotice('Enter the current connection code shown in your local file app.');}}>Reconnect this browser</Button><Button variant="ghost" disabled={!!busy} onClick={()=>setRevoke(service.serviceId)}>Remove access</Button></div>{revoke===service.serviceId&&<div className="delivery-cancel"><span>Remove this folder’s access? A new local connection must be set up to use it again.</span><Button variant="secondary" disabled={!!busy} onClick={()=>setRevoke('')}>Keep access</Button><Button variant="danger" busy={busy===service.serviceId} disabled={!!busy} onClick={()=>void revokeService(service)}>Remove access</Button></div>}</article>)}
   <section className="delivery-connect-form stack"><h3>{services.some(s=>s.state==='active')?'Connect or reconnect a folder':'Connect a shared folder'}</h3><p>Open your organisation’s local file app, choose the folder there, then enter the address and connection code it shows.</p><CompanionLinks/><Field label="Connection name"><Input value={label} maxLength={160} disabled={!!busy} onChange={e=>setLabel(e.target.value)} placeholder="For example, Studio computer"/></Field><Field label="Local file app address" hint="Use the address shown by the app. This connects only to the folder chosen there."><Input type="url" value={address} disabled={!!busy} onChange={e=>setAddress(e.target.value)} placeholder="https://localhost:3411"/></Field><Field label="Connection code" hint="Shown once by your local file app. This code is only for connecting the folder."><Input autoComplete="off" value={code} maxLength={128} disabled={!!busy} onChange={e=>setCode(e.target.value)}/></Field><Button busy={busy==='connect'} disabled={!!busy||!label.trim()||!address.trim()||!code.trim()} onClick={()=>void connect()}><Link2 size={16}/> Connect folder</Button></section>
   {notice&&<FileNotice>{notice}</FileNotice>}{error!==undefined&&<DeliveryNotice error={error}/>}
  </div>
 </Modal>;
}
