'use client';
import { useEffect, useId, useRef, useState } from 'react';
import { ArrowRight, Check, Copy, Download, Folder, Link2, Plus } from 'lucide-react';
import type { ReadableFileEntry, ReadableFileVersion } from '../../src/client/files-controller.js';
import { useApp } from '../shared/context';
import { Badge, Button, DialogTabs, EmptyState, Field, Modal, Select, Spinner } from '../shared/ui';
import { taskName, type Project } from '../work/shared';
import { bytesLabel,canDownloadFiles,canWriteFiles,canWriteFileVersion,externalWarning,FileIcon,FileNotice,updatedLabel,saveDownload,uploadLimit } from './common';
import { AddFiles } from './upload';
import { FilePreview } from './preview';
import { SharedSourceApproval } from './approval';
import { OfficeEditor } from './editor';

export function FileDetail({project,entry,pinnedVersionId,onClose,onChanged,readOnly=false}:{project:Project;entry:ReadableFileEntry;pinnedVersionId?:string;readOnly?:boolean;onClose:()=>void;onChanged:()=>void|Promise<void>}){
 const {client,notify,navigate}=useApp(),projectId=project.graph.project.id,[tab,setTab]=useState('preview'),tabsId=useId(),[selected,setSelected]=useState<ReadableFileVersion>({...entry.version,metadata:entry.metadata}),[pinReady,setPinReady]=useState(!pinnedVersionId||pinnedVersionId===entry.latestVersionId),[versions,setVersions]=useState<ReadableFileVersion[]>([]),[next,setNext]=useState<string|null>(null),[bytes,setBytes]=useState<Uint8Array>(),[error,setError]=useState<unknown>(),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[dialog,setDialog]=useState<'version'|'link'|'edit'|null>(null),[verified,setVerified]=useState(false),picker=useRef<HTMLInputElement>(null),epoch=useRef(0),externalBytes=useRef<Uint8Array|undefined>(undefined),download=canDownloadFiles(project),write=!readOnly&&canWriteFileVersion(project,entry),selectedId=selected.manifest.body.versionId,external=selected.manifest.body.storage==='external';
 useEffect(()=>{if(!pinnedVersionId||pinnedVersionId===entry.latestVersionId)return;let alive=true;setPinReady(false);setLoading(true);void client.files.version(projectId,pinnedVersionId).then(v=>{if(alive){setSelected(v);setPinReady(true);}}).catch(e=>{if(alive)setError(e);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[client,projectId,pinnedVersionId,entry.latestVersionId]);
 useEffect(()=>{const stamp=++epoch.current;externalBytes.current?.fill(0);externalBytes.current=undefined;setBytes(undefined);setVerified(false);if(!pinReady)return;setError(undefined);if(tab!=='preview'||external)return;setLoading(true);let loaded:Uint8Array|undefined;void client.files.bytes(projectId,selectedId,'preview').then(result=>{loaded=result.bytes;if(stamp===epoch.current)setBytes(loaded);else loaded.fill(0);}).catch(e=>{if(stamp===epoch.current)setError(e);}).finally(()=>{if(stamp===epoch.current)setLoading(false);});return()=>{epoch.current++;loaded?.fill(0);externalBytes.current?.fill(0);};},[client,projectId,selectedId,tab,external,pinReady]);
 useEffect(()=>{if(tab!=='versions')return;let alive=true;setLoading(true);setError(undefined);void client.files.versions(projectId,entry.fileId).then(v=>{if(alive){setVersions(v.versions);setNext(v.nextVersion);}}).catch(e=>{if(alive)setError(e);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[client,projectId,entry.fileId,tab]);
 async function moreVersions(){if(!next||loading)return;setLoading(true);try{const page=await client.files.versions(projectId,entry.fileId,next);setVersions(old=>[...old,...page.versions]);setNext(page.nextVersion);}catch(e){setError(e);}finally{setLoading(false);}}
 async function getDownload(){setBusy(true);setError(undefined);try{const result=await client.files.bytes(projectId,selectedId,'download');try{saveDownload(result.bytes,result.metadata.filename,result.metadata.mediaType);notify('Download prepared. Keep this file private.');}finally{result.bytes.fill(0);}}catch(e){setError(e);}finally{setBusy(false);}}
 async function checkExternal(file:File|undefined){if(!file||!pinReady)return;const stamp=epoch.current;setBusy(true);setError(undefined);setVerified(false);try{const result=await client.files.verifyExternal(projectId,selectedId,file);if(stamp!==epoch.current)return;if(!result.matches){setError({code:'CHANGED_FILE'});return;}setVerified(true);if(file.size<=uploadLimit){const chosen=new Uint8Array(await file.arrayBuffer());if(stamp!==epoch.current){chosen.fill(0);return;}externalBytes.current?.fill(0);externalBytes.current=chosen;setBytes(chosen);}notify('The selected file matches this version.');}catch(e){if(stamp===epoch.current)setError(e);}finally{if(stamp===epoch.current)setBusy(false);}}
 async function copyPath(){try{await navigator.clipboard.writeText(selected.metadata.path??'');notify('Location copied.');}catch{notify('Select and copy the location shown below.','info');}}
 function showVersion(v:ReadableFileVersion){setSelected(v);setTab('preview');}
 const title=pinReady?selected.metadata.filename:'Opening linked version…',subtitle=<span className="task-subtitle"><span>{selected.metadata.documentReference}</span><Badge>{entry.kind==='source'?'Source':'Output'}</Badge><Badge>Version {selected.manifest.body.version}</Badge></span>;
 return <><Modal open layout="detail" expandable title={title} description={pinReady?subtitle:<span>Checking this task’s linked version…</span>} onClose={onClose} scrollKey={tab} navigation={<DialogTabs id={tabsId} label="File details" value={tab} tabs={[{id:'preview',label:'Preview'},{id:'versions',label:'Versions'},{id:'links',label:'Linked work'},...(entry.kind==='source'?[{id:'approval',label:'Approval'}]:[])]} onChange={setTab}/>} footer={<><span className="file-footer-summary">{bytesLabel(selected.manifest.body.plainBytes)} · {external?'Shared drive':'Uploaded'}</span><Button variant="secondary" onClick={onClose}>Close</Button>{download&&!external&&<Button variant="secondary" busy={busy} disabled={!pinReady} onClick={()=>void getDownload()}><Download size={16}/> Download v{selected.manifest.body.version}</Button>}{write&&<Button onClick={()=>setDialog('version')}><Plus size={16}/> Add version</Button>}</>}>
  <div className="files-dialog stack">{error!==undefined&&<FileNotice error={error}/>}
   <section hidden={tab!=='preview'} role="tabpanel" className="dialog-tabpanel" id={tabsId+'-panel-preview'} aria-labelledby={tabsId+'-tab-preview'}>
    {pinReady&&write&&!external&&selectedId===entry.latestVersionId&&/\.(docx|xlsx|pptx)$/i.test(title)&&<div className="file-preview-actions"><Button variant="secondary" onClick={()=>setDialog('edit')}>Open for editing</Button></div>}
    {pinReady&&external&&<div className="stack"><FileNotice warning>{externalWarning}</FileNotice><div className="file-location"><Folder size={19}/><div><span className="muted">Shared-drive location</span><p className="preserve-lines">{selected.metadata.path}</p></div><Button variant="ghost" onClick={()=>void copyPath()} aria-label="Copy shared-drive location"><Copy size={17}/></Button></div><input className="sr-only" ref={picker} type="file" aria-label="Choose the external file to check" onChange={e=>{void checkExternal(e.target.files?.[0]);e.target.value='';}}/><div className="file-verify"><Badge tone={verified?'success':'warning'}>{verified?<><Check size={13}/> Matches this version</>:'Choose the file to check'}</Badge><Button variant="secondary" busy={busy} onClick={()=>picker.current?.click()}>Check selected file</Button></div>{selected.manifest.body.plainBytes>uploadLimit&&<p className="muted">This large file can be checked here. Open it from your shared drive to work on it.</p>}</div>}
    {loading?<div className="files-loading"><Spinner/><span>Opening this version…</span></div>:bytes?<FilePreview bytes={bytes} filename={title}/>:pinReady&&!external&&!error?<EmptyState title="Preview unavailable" description="Download this version to open it in your preferred application."/>:null}
    <details className="file-external-work"><summary>Work on your computer</summary><p>After editing on your computer, upload the updated file. Changes do not sync automatically.</p>{write&&<Button variant="secondary" onClick={()=>setDialog('version')}><FileIcon name={title}/> Add new version</Button>}</details>
   </section>
   <section hidden={tab!=='versions'} role="tabpanel" className="dialog-tabpanel stack" id={tabsId+'-panel-versions'} aria-labelledby={tabsId+'-tab-versions'}><p className="muted">Earlier reviews keep their exact versions.</p>{versions.filter(v=>v.state==='ready').map(v=>{const person=project.authority.accountId===v.manifest.body.binding.accountId?'You':undefined;return <article className="file-version-row" key={v.manifest.body.versionId}><span className="file-version-number">v{v.manifest.body.version}</span><div><strong>Version {v.manifest.body.version}</strong>{v.manifest.body.versionId===entry.latestVersionId&&<Badge>Current working version</Badge>}<p className="muted">{person?person+' · ':''}{updatedLabel(v.completedAt)} · {bytesLabel(v.manifest.body.plainBytes)}</p></div><Button variant="secondary" onClick={()=>showVersion(v)}>Open version <ArrowRight size={15}/></Button></article>;})}{loading&&<Spinner/>}{next&&<Button variant="secondary" busy={loading} onClick={()=>void moreVersions()}>Load more versions</Button>}</section>
   <section hidden={tab!=='links'} role="tabpanel" className="dialog-tabpanel stack" id={tabsId+'-panel-links'} aria-labelledby={tabsId+'-tab-links'}><div className="section-heading"><div><h3>Linked work</h3><p className="muted">One file, shared across the work that needs it.</p></div>{write&&<Button variant="secondary" onClick={()=>setDialog('link')}><Link2 size={15}/> Link to tasks</Button>}</div>{entry.links.map(link=><button className="file-linked-task" key={link.taskId} onClick={()=>{onClose();navigate({page:'project',projectId,tab:'work',taskId:link.taskId});}}><span><strong>{taskName(project,link.taskId)}</strong><small className="muted">{link.mode==='latest'?'Latest working version':'An exact version is pinned'}</small></span><ArrowRight size={17}/></button>)}{!entry.links.length&&<EmptyState title="A project reference" description="This file has not been linked to a task yet. It remains available to people who can read this project."/>}</section>
   {entry.kind==='source'&&tab==='approval'&&pinReady&&<section role="tabpanel" className="dialog-tabpanel" id={tabsId+'-panel-approval'} aria-labelledby={tabsId+'-tab-approval'}><SharedSourceApproval project={project} version={selected} onChanged={onChanged}/></section>}
  </div>
 </Modal>{dialog==='edit'&&<OfficeEditor project={project} version={selected} onClose={()=>setDialog(null)} onSaved={onChanged}/>} {dialog==='version'&&<AddFiles project={project} versionOf={entry} onClose={()=>setDialog(null)} onSaved={onChanged}/>} {dialog==='link'&&<LinkFiles project={project} entry={entry} versionId={selectedId} onClose={()=>setDialog(null)} onSaved={onChanged}/>}</>;
}

export function LinkFiles({project,entry,versionId,onClose,onSaved}:{project:Project;entry:ReadableFileEntry;versionId:string;onClose:()=>void;onSaved:()=>void|Promise<void>}){
 const {client}=useApp(),[tasks,setTasks]=useState<string[]>([]),[mode,setMode]=useState<'latest'|'pinned'>('latest'),[busy,setBusy]=useState(false),[error,setError]=useState<unknown>();
 const available=project.graph.tasks.filter(t=>!['done','cancelled'].includes(t.state)&&(project.authority.isOwner||project.authority.permissions.includes('manage_tasks')||project.authority.permissions.includes('plan_projects')||t.assigneeIds.includes(project.authority.accountId)));
 async function save(){setBusy(true);setError(undefined);try{await client.files.link(project.graph.project.id,{fileId:entry.fileId,taskIds:tasks,action:'link',mode,versionId:mode==='pinned'?versionId:null});await onSaved();onClose();}catch(e){setError(e);}finally{setBusy(false);}}
 return <Modal open layout="form" title="Link file to work" description={entry.metadata.filename} onClose={()=>{if(!busy)onClose();}} footer={<><Button variant="secondary" disabled={busy} onClick={onClose}>Cancel</Button><Button busy={busy} disabled={!tasks.length} onClick={()=>void save()}>Link to {tasks.length||''} {tasks.length===1?'task':'tasks'}</Button></>}><div className="stack"><Field label="Working version"><Select value={mode} onChange={e=>setMode(e.target.value as typeof mode)} disabled={busy}><option value="latest">Use the latest working version</option><option value="pinned">Pin the version I am viewing</option></Select></Field><p className="muted">Submitted evidence always records an exact version, even when a task uses the latest working file.</p><div className="file-task-picker">{available.map(task=><label className="check-row" key={task.id}><input type="checkbox" checked={tasks.includes(task.id)} disabled={busy||tasks.length>=64&&!tasks.includes(task.id)} onChange={e=>setTasks(old=>e.target.checked?[...old,task.id]:old.filter(id=>id!==task.id))}/><span>{taskName(project,task.id)}</span></label>)}</div>{!available.length&&<p className="muted">There are no editable tasks available. A project manager can help.</p>}{error!==undefined&&<FileNotice error={error}/>}</div></Modal>;
}
