'use client';
import dynamic from 'next/dynamic';
import { useCallback,useEffect,useRef,useState } from 'react';
import type { Config } from '@onlyoffice/doceditor-types';
import type { DocumentEditorProps } from '@onlyoffice/document-editor-react';
import { FilePenLine } from 'lucide-react';
import type { FileEditorLease } from '../../src/client/file-editor-controller.js';
import type { ReadableDeliveryService } from '../../src/client/files-delivery-controller.js';
import type { ReadableFileVersion } from '../../src/client/files-controller.js';
import { useApp } from '../shared/context';
import { Badge,Button,EmptyState,Field,Modal,Select,Spinner } from '../shared/ui';
import { type Project } from '../work/shared';
import { FileNotice } from './common';

const DocumentEditor=dynamic<DocumentEditorProps>(()=>import('@onlyoffice/document-editor-react').then(m=>m.DocumentEditor),{ssr:false,loading:()=> <div className="files-loading"><Spinner/> Opening the editor…</div>});
export function OfficeEditor({project,version,onClose,onSaved}:{project:Project;version:ReadableFileVersion;onClose:()=>void;onSaved:()=>void|Promise<void>}){
 const {client,theme,notify,navigate}=useApp(),[services,setServices]=useState<ReadableDeliveryService[]>([]),[selected,setSelected]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[lease,setLease]=useState<FileEditorLease>(),[error,setError]=useState<unknown>(),[ready,setReady]=useState(false),[dirty,setDirty]=useState(false),[leave,setLeave]=useState(false),alive=useRef(true),held=useRef<FileEditorLease|undefined>(undefined),projectId=project.graph.project.id;
 const load=useCallback(async()=>{setLoading(true);setError(undefined);try{const values=(await client.fileEditor.services(projectId)).filter(v=>v.state==='active');if(alive.current){setServices(values);setSelected(values[0]?.serviceId??'');}}catch(e){if(alive.current)setError(e);}finally{if(alive.current)setLoading(false);}},[client,projectId]);
 useEffect(()=>{alive.current=true;void load();return()=>{alive.current=false;if(held.current)void client.fileEditor.close(held.current);held.current=undefined;};},[client,load]);
 useEffect(()=>{if(!dirty)return;const stop=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',stop);return()=>window.removeEventListener('beforeunload',stop);},[dirty]);
 useEffect(()=>{if(!lease||ready)return;const timeout=setTimeout(()=>{if(alive.current)setError({code:'UNAVAILABLE'});},30000);return()=>clearTimeout(timeout);},[lease,ready]);
 async function open(){if(!selected)return;setBusy(true);setError(undefined);try{const next=await client.fileEditor.open(projectId,version.manifest.body.versionId,selected,{theme:theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):theme});if(!alive.current){await client.fileEditor.close(next);return;}held.current=next;setLease(next);setReady(false);setDirty(false);}catch(e){if(alive.current)setError(e);}finally{if(alive.current)setBusy(false);}}
 async function save(){if(!lease)return;setBusy(true);setError(undefined);try{const result=await client.fileEditor.save(lease);if(!alive.current)return;held.current=undefined;setDirty(false);notify(result.state==='saved'?'A new version is saved. Earlier versions are unchanged.':'There were no changes to save.');await onSaved();onClose();}catch(e){if(alive.current)setError(e);}finally{if(alive.current)setBusy(false);}}
 async function discard(){if(held.current)await client.fileEditor.close(held.current);held.current=undefined;setDirty(false);onClose();}
 async function retryOpening(){if(busy||dirty||ready)return;if(held.current)await client.fileEditor.close(held.current);held.current=undefined;setLease(undefined);await open();}
 function close(){if(busy){notify('Wait for the current editing step to finish.','info');return;}if(dirty){setLeave(true);return;}void discard();}
 const unavailable=error&&typeof error==='object'&&'code'in error&&/UNAVAILABLE|NETWORK|OFFLINE/.test(String(error.code)),conflict=error&&typeof error==='object'&&'code'in error&&/CONFLICT|CHANGED|STALE/.test(String(error.code));
 return <><Modal open layout="detail" title={version.metadata.filename} description={<span className="task-subtitle"><span>Editing from v{version.manifest.body.version}</span><Badge>New version on save</Badge></span>} onClose={close} footer={<><span className="file-footer-summary">{lease?dirty?'Changes have not been saved to Maqbool.':'Your earlier version is kept.':'Your organisation’s editor processes this document.'}</span><Button variant="secondary" disabled={busy} onClick={close}>{lease?'Close':'Cancel'}</Button>{lease?<Button busy={busy} disabled={!ready||!!conflict} onClick={()=>void save()}>Save new version</Button>:services.length>0?<Button busy={busy} disabled={!selected} onClick={()=>void open()}>Open for editing</Button>:null}</>}>
  <div className="file-editor-content stack">{error!==undefined&&(unavailable?<FileNotice warning>The editor is unavailable. Your saved file is safe. Allow local network access if your browser asks, then try again. You can also work on your computer.</FileNotice>:conflict?<FileNotice warning>A newer version or your access changed while this file was open. Close this editor and review the current file before continuing.</FileNotice>:<FileNotice error={error}/>)}
  {(!!unavailable||!loading&&!lease&&!services.length)&&<p className="field-hint"><a href="/downloads/maqbool-local-mac.zip" download>Get the Mac companion</a><span aria-hidden="true"> · </span><a href="/local-files-help.html" target="_blank" rel="noopener noreferrer">Setup guide</a></p>}
  {loading?<div className="files-loading"><Spinner/> Checking your organisation’s editor…</div>:lease?<><div className="file-editor-stage">{!ready&&<div className="file-editor-opening" role="status">{!unavailable?<><Spinner/><span>Opening your document…</span></>:<span>Unable to open this document. Close to work on your computer.</span>}</div>}<DocumentEditor key={lease.leaseId} id={'maqbool-office-'+lease.leaseId} documentServerUrl={lease.address+'/office/'} config={lease.config as unknown as Config} width="100%" height="100%" events_onDocumentReady={()=>{setReady(true);setError(undefined);}} events_onDocumentStateChange={event=>{if('data'in event&&event.data===true)setDirty(true);}} events_onError={()=>setError({code:'UNAVAILABLE'})} onLoadComponentError={()=>setError({code:'UNAVAILABLE'})}/></div>{unavailable&&!ready&&!dirty&&<Button variant="secondary" busy={busy} onClick={()=>void retryOpening()}>Try opening again</Button>}</>:services.length?<><Field label="Organisation editor"><Select value={selected} onChange={e=>setSelected(e.target.value)} disabled={busy}>{services.map(service=><option key={service.serviceId} value={service.serviceId}>{service.metadata.label}</option>)}</Select></Field><p className="muted">Edit this document here, then save a new version in Maqbool.</p></>:<EmptyState icon={<FilePenLine/>} title="Editing is not set up yet" description="You can work on your computer today. An Owner can connect your organisation’s editor from Delivery." action={<Button variant="secondary" onClick={()=>{onClose();navigate({page:'project',projectId,tab:'delivery'});}}>View shared-folder setup</Button>}/>}
  {!lease&&<p className="field-hint">After editing on your computer, upload the updated file. Changes do not sync automatically.</p>}{!lease&&error!==undefined&&<Button variant="secondary" disabled={busy} onClick={()=>void load()}>Check editor again</Button>}
  </div>
 </Modal>{leave&&<Modal open layout="form" title="Leave without saving?" description="Your changes have not been saved as a version in Maqbool." onClose={()=>setLeave(false)} footer={<><Button variant="secondary" onClick={()=>setLeave(false)}>Keep editing</Button><Button variant="danger" onClick={()=>void discard()}>Discard changes</Button></>}><p>Close this editing session and keep the last saved version.</p></Modal>}</>;
}
