'use client';
import { useMemo, useState } from 'react';
import { ArrowUpRight, FileText, Folder, Plus, Search } from 'lucide-react';
import { useApp } from '../shared/context';
import { Badge, Button, EmptyState, Input, Select, Spinner } from '../shared/ui';
import type { ReadableFileEntry } from '../../src/client/files-controller.js';
import { has,type Project } from '../work/shared';
import { bytesLabel,canDownloadFiles,canWriteFiles,FileIcon,FileNotice,FilesLoading,StorageMeter,updatedLabel,useFiles } from './common';
import { AddFiles } from './upload';
import { FileDetail } from './detail';
import { PendingUploads } from './storage';
import { BulkFiles,SavedBatches } from './bulk';
import { FilesMenu } from './menu';
import { ExportFiles } from './archive';

export function ProjectFiles({project}:{project:Project}){
 const {navigate,directory}=useApp(),files=useFiles(project),[query,setQuery]=useState(''),[kind,setKind]=useState(''),[location,setLocation]=useState(''),[selected,setSelected]=useState<ReadableFileEntry>(),[dialog,setDialog]=useState<'upload'|'external'|'pending'|'register'|'assign'|'submit'|'batches'|'export'|null>(null),write=canWriteFiles(project)&&directory?.lifecycle==='active',canDownload=canDownloadFiles(project);
 const rows=useMemo(()=>files.entries.filter(e=>(!kind||e.kind===kind)&&(!location||e.version.manifest.body.storage===location)&&(!query||[e.metadata.filename,e.metadata.documentReference,e.metadata.label].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase()))),[files.entries,query,kind,location]);
 const close=()=>setSelected(undefined);
 return <div className="files-page stack"><header className="files-heading"><div><h2>Files</h2><p>Sources and outputs for your project.</p></div><div className="button-row"><FilesMenu actions={[...(write?[{label:'Keep on shared drive',onClick:()=>setDialog('external')}]:[]),...(write&&(project.authority.isOwner||has(project,'manage_tasks')||has(project,'plan_projects'))?[{label:'Register documents',onClick:()=>setDialog('register')},{label:'Assign document work',onClick:()=>setDialog('assign')}]:[]),...(write?[{label:'Submit outputs',onClick:()=>setDialog('submit')}]:[]),...(canDownload?[{label:'Export files',onClick:()=>setDialog('export')}]:[]),{label:'Saved batches',onClick:()=>setDialog('batches')},{label:'Unfinished uploads',onClick:()=>setDialog('pending')}]} />{write&&<Button onClick={()=>setDialog('upload')}><Plus size={16}/> Add files</Button>}</div></header>
  <div className="files-toolbar"><div className="search-field"><Search size={17}/><Input aria-label="Find a file or document reference" placeholder="Find a file or document reference…" value={query} onChange={e=>setQuery(e.target.value)}/></div><Select aria-label="Filter by purpose" value={kind} onChange={e=>setKind(e.target.value)}><option value="">All files</option><option value="source">Sources</option><option value="output">Outputs</option></Select><Select aria-label="Filter by location" value={location} onChange={e=>setLocation(e.target.value)}><option value="">All locations</option><option value="managed">Uploaded</option><option value="external">Shared drive</option></Select><Button variant="ghost" busy={files.loading} onClick={()=>void files.reload()}>Refresh</Button></div>
  {files.error!==undefined&&<FileNotice error={files.error} action={<Button variant="ghost" onClick={()=>void files.reload()}>Try again</Button>}/>}
  {files.loading&&!files.entries.length?<FilesLoading/>:rows.length?<div className="files-table-card"><div className="table-wrap"><table className="table files-table"><thead><tr><th scope="col">Name & reference</th><th scope="col">Purpose</th><th scope="col">Version</th><th scope="col">Linked work</th><th scope="col">Location</th><th scope="col">Updated</th><th scope="col"><span className="sr-only">Open file</span></th></tr></thead><tbody>{rows.map(entry=><tr key={entry.fileId}><td><button className="file-name-button" onClick={()=>setSelected(entry)}><FileIcon name={entry.metadata.filename}/><span><strong>{entry.metadata.filename}</strong><small>{entry.metadata.documentReference} · {bytesLabel(entry.version.manifest.body.plainBytes)}</small></span></button></td><td><Badge tone={entry.kind==='output'?'purple':'neutral'}>{entry.kind==='output'?'Output':'Source'}</Badge></td><td><span className="file-version-label">v{entry.version.manifest.body.version}</span></td><td><span className="muted">{entry.links.length?entry.links.length+(entry.links.length===1?' task':' tasks'):'Project reference'}</span></td><td><Badge tone={entry.version.manifest.body.storage==='external'?'warning':'neutral'}>{entry.version.manifest.body.storage==='external'?'Shared drive':'Uploaded'}</Badge></td><td className="muted">{updatedLabel(entry.version.completedAt)}</td><td><button className="icon-button" aria-label={'Open '+entry.metadata.filename} onClick={()=>setSelected(entry)}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div></div>:files.entries.length?<EmptyState title="No files match" description="Try another reference or clear your filters." icon={<Search/>} action={<Button variant="secondary" onClick={()=>{setQuery('');setKind('');setLocation('');}}>Clear filters</Button>}/>:!files.error&&<div className="files-table-card"><EmptyState title="Your project files start here" description="Keep sources and outputs together. Link shared documents to the tasks that need them." icon={<FileText/>} action={write?<div className="button-row"><Button onClick={()=>setDialog('upload')}>Add files</Button><Button variant="secondary" onClick={()=>setDialog('external')}>Keep on shared drive</Button></div>:<Button variant="secondary" onClick={()=>navigate({page:'project',projectId:project.graph.project.id,tab:'work'})}>Back to work</Button>}/></div>}
  <div className="files-list-footer"><span>{files.entries.length} {files.entries.length===1?'file':'files'} loaded{files.next?' · More available':''}</span><div className="button-row">{files.quota&&<span>{bytesLabel(files.quota.usedBytes+files.quota.reservedBytes)} of {bytesLabel(files.quota.limitBytes)} used</span>}<Button variant="ghost" onClick={()=>navigate({page:'settings',section:'data'})}>View storage</Button>{files.next&&<Button variant="secondary" busy={files.loading} onClick={()=>void files.loadMore()}>Load more files</Button>}</div></div>
  {!canDownload&&<p className="file-access-note">You can view project files. Ask an Owner for download access.</p>}
  {selected&&<FileDetail key={selected.fileId} project={project} entry={files.entries.find(e=>e.fileId===selected.fileId)??selected} onClose={close} onChanged={files.reload}/>}
  {(dialog==='upload'||dialog==='external')&&<AddFiles project={project} initialStorage={dialog==='external'?'external':'managed'} onClose={()=>setDialog(null)} onSaved={files.reload}/>}
  {(dialog==='register'||dialog==='assign'||dialog==='submit')&&<BulkFiles project={project} mode={dialog} onClose={()=>setDialog(null)} onSaved={files.reload}/>}
  {dialog==='batches'&&<SavedBatches project={project} onClose={()=>setDialog(null)} onSaved={files.reload}/>}
  {dialog==='export'&&<ExportFiles project={project} onClose={()=>setDialog(null)}/>}
  {dialog==='pending'&&<PendingUploads project={project} onClose={()=>setDialog(null)} onChanged={files.reload}/>}
 </div>;
}
