'use client';
import { useCallback, useEffect, useState } from 'react';
import { ArrowRight, Folder, HardDrive, RefreshCw } from 'lucide-react';
import type { StoredFileUpload } from '../../src/client/files-store.js';
import type { FileQuota } from '../../src/shared/files.js';
import { useApp } from '../shared/context';
import { Badge, Button, EmptyState, Modal, Spinner } from '../shared/ui';
import { type Project } from '../work/shared';
import { bytesLabel,FileIcon,FileNotice,StorageMeter,updatedLabel } from './common';

type PendingRow={record:StoredFileUpload;filename:string;createdAt:string};
export function PendingUploads({project,onClose,onChanged}:{project?:Project;onClose:()=>void;onChanged?:()=>void|Promise<void>}){
 const {client,notify}=useApp(),[rows,setRows]=useState<PendingRow[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState<unknown>(),[progress,setProgress]=useState<{completed:number;total:number}>();
 const read=useCallback(async()=>{setLoading(true);setError(undefined);try{const records=(await client.files.pending()).filter(r=>!project||r.manifest.body.binding.projectId===project.graph.project.id),result:PendingRow[]=[];for(const record of records){let filename='Unfinished upload';try{const v=await client.files.version(record.manifest.body.binding.projectId,record.manifest.body.versionId);filename=v.metadata.filename;}catch{}result.push({record,filename,createdAt:record.manifest.body.binding.issuedAt});}setRows(result);}catch(e){setError(e);}finally{setLoading(false);}},[client,project?.graph.project.id]);
 useEffect(()=>{void read();},[read]);
 async function act(row:PendingRow,resume:boolean){setBusy(row.record.operationId);setError(undefined);setProgress(undefined);try{if(resume)await client.files.resume(row.record.operationId,p=>setProgress({completed:p.completedBytes,total:p.totalBytes}));else await client.files.cancel(row.record.operationId);notify(resume?'Your file is saved.':'The unfinished attempt was checked. Saved files were kept.');await read();await onChanged?.();}catch(e){setError(e);}finally{setBusy('');setProgress(undefined);}}
 return <Modal open layout="form" title="Unfinished uploads" description="Check saved attempts before trying the same file again." onClose={()=>{if(!busy)onClose();}} footer={<Button variant="secondary" disabled={!!busy} onClick={onClose}>Close</Button>}><div className="stack"><FileNotice>Completed files are kept. Storage from a cancelled unfinished upload is released only after the change is confirmed.</FileNotice>{error!==undefined&&<FileNotice error={error} action={<Button variant="ghost" onClick={()=>void read()}>Check again</Button>}/>} {loading?<div className="files-loading"><Spinner/> Checking saved attempts…</div>:rows.length?<div className="file-pending-list">{rows.map(row=><article className="file-pending-row" key={row.record.operationId}><FileIcon name={row.filename}/><div><strong>{row.filename}</strong><p className="muted">{bytesLabel(row.record.manifest.body.plainBytes)} · Started {updatedLabel(row.createdAt)}</p><Badge tone="warning">Unfinished</Badge>{busy===row.record.operationId&&progress&&<p aria-live="polite">{bytesLabel(progress.completed)} of {bytesLabel(progress.total)}</p>}</div><div className="button-row"><Button variant="secondary" busy={busy===row.record.operationId} disabled={!!busy&&busy!==row.record.operationId} onClick={()=>void act(row,true)}>Resume</Button><Button variant="ghost" disabled={!!busy} onClick={()=>void act(row,false)}>Cancel attempt</Button></div></article>)}</div>:<EmptyState icon={<HardDrive/>} title="Everything is up to date" description="There are no unfinished file uploads on this browser."/>}</div></Modal>;
}

export function FileStorage(){
 const {client,projects,navigate,directory}=useApp(),[quota,setQuota]=useState<FileQuota>(),[error,setError]=useState<unknown>(),[loading,setLoading]=useState(false),[pending,setPending]=useState(false),project=projects[0];
 const refresh=useCallback(async()=>{if(!project)return;setLoading(true);setError(undefined);try{const result=await client.files.context(project.graph.project.id);setQuota(result.quota);}catch(e){setError(e);}finally{setLoading(false);}},[client,project?.graph.project.id]);
 useEffect(()=>{void refresh();},[refresh]);
 return <section className="card files-storage-card"><div className="section-heading"><div><h2>File storage</h2><p className="muted">Uploaded files, earlier versions and unfinished uploads.</p></div><HardDrive size={22}/></div>{error!==undefined&&<FileNotice error={error} action={<Button variant="ghost" onClick={()=>void refresh()}>Try again</Button>}/>} {loading&&!quota?<div className="files-loading"><Spinner/> Checking storage…</div>:quota?<><StorageMeter quota={quota}/>{quota.reservedBytes>0&&<p className="field-hint">{bytesLabel(quota.reservedBytes)} reserved for unfinished uploads.</p>}</>:<p className="muted">Create a project to start keeping files with your work.</p>}<p className="field-hint">25 MiB per upload · 64 items or 250 MiB per batch · 512 document tasks per project</p><p className="field-hint">Shared-drive files are references only. Their contents are not included in cloud backups or downloads. Your organisation must back up those files.</p><div className="button-row"><Button variant="secondary" onClick={()=>setPending(true)}>Manage unfinished uploads</Button>{project&&<Button variant="secondary" onClick={()=>navigate({page:'project',projectId:project.graph.project.id,tab:'files'})}><Folder size={15}/> View project files <ArrowRight size={15}/></Button>}<Button variant="ghost" busy={loading} disabled={!project} onClick={()=>void refresh()}><RefreshCw size={15}/> Refresh storage</Button></div>{pending&&<PendingUploads onClose={()=>setPending(false)} onChanged={refresh}/>}</section>;
}
