'use client';
import { useRef, useState } from 'react';
import { Check, FileUp, Folder, Plus, Trash2, Upload } from 'lucide-react';
import type { ReadableFileEntry, UploadFileInput } from '../../src/client/files-controller.js';
import { useApp } from '../shared/context';
import { Badge, Button, DialogTabs, Field, Input, Modal, Select, Spinner } from '../shared/ui';
import { taskName, type Project } from '../work/shared';
import { canManageFiles,batchBytes,batchLimit,bytesLabel,externalLimit,externalWarning,fileAccept,FileIcon,FileNotice,supported,uploadLimit,extension } from './common';

type Row={id:string;operationId:string;file:File;reference:string;kind:'source'|'output';taskId:string;path:string;storage:'managed'|'external';state:'ready'|'preparing'|'uploading'|'saved'|'error';completed:number;error?:unknown;locked:boolean};
export function AddFiles({project,taskId,versionOf,onClose,onSaved,initialStorage='managed',initialKind='source'}:{project:Project;taskId?:string;versionOf?:ReadableFileEntry;onClose:()=>void;onSaved:()=>void|Promise<void>;initialStorage?:'managed'|'external';initialKind?:'source'|'output'}){
 const {client,notify}=useApp(),[storage,setStorage]=useState<'managed'|'external'>(versionOf?.version.manifest.body.storage??initialStorage),[rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),picker=useRef<HTMLInputElement>(null),running=useRef(false),cancelled=useRef(new Set<string>()),[cancelling,setCancelling]=useState<string[]>([]),[tabId]=useState(()=>crypto.randomUUID());
 const manager=canManageFiles(project),projectId=project.graph.project.id,activeTasks=project.graph.tasks.filter(t=>!['review','done','cancelled'].includes(t.state)&&!project.graph.project.archived&&(project.authority.isOwner||project.authority.permissions.includes('manage_tasks')||project.authority.permissions.includes('plan_projects')||t.assigneeIds.includes(project.authority.accountId)));
 function update(id:string,values:Partial<Row>){if(cancelled.current.has(id))return;setRows(old=>old.map(r=>r.id===id?{...r,...values}:r));}
 function choose(files:FileList|null){if(!files)return;const selected=Array.from(files);if(rows.length+selected.length>batchLimit||versionOf&&selected.length+rows.length>1){setNotice(versionOf?'Choose one file for this version.':'Choose up to 64 files in one batch.');return;}const bytes=rows.reduce((a,r)=>a+(r.storage==='managed'?r.file.size:0),0)+selected.reduce((a,f)=>a+(storage==='managed'?f.size:0),0);if(bytes>batchBytes){setNotice('Uploads in one batch must total 250 MiB or less. Choose fewer files, or keep large files on your shared drive.');return;}setNotice('');setRows(old=>[...old,...selected.map(file=>({id:crypto.randomUUID(),operationId:crypto.randomUUID(),file,reference:versionOf?.metadata.documentReference??'',kind:versionOf?.kind??(manager?initialKind:'output'),taskId:taskId??versionOf?.links.find(l=>l.mode==='latest')?.taskId??'',path:'',storage,state:'ready' as const,completed:0,locked:false}))]);}
 async function save(){
  if(running.current)return;setNotice('');const ready=rows.filter(r=>r.state!=='saved');
  const invalid=ready.find(r=>!r.reference.trim()||!manager&&!r.taskId||r.storage==='external'&&!r.path.trim()||r.file.size<1||r.file.size>(r.storage==='managed'?uploadLimit:externalLimit)||r.storage==='managed'&&!supported.includes(extension(r.file.name)));
  if(ready.reduce((total,row)=>total+(row.storage==='managed'?row.file.size:0),0)>batchBytes){setNotice('Uploads in one batch must total 250 MiB or less. Choose fewer files.');return;}
  if(invalid){setNotice('Check the highlighted file and complete its document reference and location before saving.');return;}
  const duplicates=ready.filter(r=>!versionOf&&ready.some(o=>o.id!==r.id&&o.reference.trim().toLowerCase()===r.reference.trim().toLowerCase()));
  if(duplicates.length){setNotice('Each new document needs a different reference. Change the repeated references before saving.');return;}
  running.current=true;setBusy(true);
  try{let cursor=0;await Promise.all(Array.from({length:Math.min(2,ready.length)},async()=>{while(cursor<ready.length){const r=ready[cursor++]!;if(cancelled.current.has(r.id))continue;update(r.id,{state:'preparing',locked:true,error:undefined});try{await client.files.upload({projectId,file:r.file,documentReference:r.reference.trim(),kind:r.kind,storage:r.storage,operationId:r.operationId,...(r.storage==='external'?{path:r.path.trim()}:{}),...(r.taskId?{taskIds:[r.taskId]}:{}),...(versionOf?{fileId:versionOf.fileId,expectedVersionId:versionOf.latestVersionId}:{}),onProgress:p=>update(r.id,{state:p.state==='saved'?'saved':p.state==='uploading'?'uploading':'preparing',completed:p.completedBytes})});update(r.id,{state:'saved',completed:r.file.size,error:undefined});}catch(error){update(r.id,{state:'error',error});}}}));await onSaved();}finally{running.current=false;setBusy(false);}
 }
 async function cancelRow(r:Row){cancelled.current.add(r.id);setCancelling(old=>[...old,r.id]);try{await client.files.cancel(r.operationId);setRows(old=>old.filter(x=>x.id!==r.id));await onSaved();if(r.locked)notify('Attempt checked. Any file already saved remains available.','info');}catch(e){cancelled.current.delete(r.id);update(r.id,{error:e,state:'error'});}finally{setCancelling(old=>old.filter(id=>id!==r.id));}}
 function close(){if(busy){notify('Your files are still being saved. Wait for the result before closing.','info');return;}onClose();}
 const saved=rows.filter(r=>r.state==='saved').length,unfinished=rows.length-saved;
 return <Modal open layout="detail" title={versionOf?'Add a new version':'Add files'} description={versionOf?'Earlier versions and their reviews stay unchanged.':'Upload a source or output, or keep the file on your shared drive.'} onClose={close} scrollKey={storage} navigation={<DialogTabs id={tabId} label="Where files are stored" value={storage} tabs={[{id:'managed',label:'Upload files'},{id:'external',label:'Keep on shared drive'}]} onChange={value=>{if(busy)return;setStorage(value as typeof storage);}}/>} footer={<><span className="file-footer-summary" aria-live="polite">{saved>0?saved+' saved · '+unfinished+' unfinished':rows.length?rows.length+' selected':'Choose files to begin'}</span><Button variant="secondary" disabled={busy} onClick={close}>{saved?'Done':'Cancel'}</Button><Button busy={busy} disabled={!rows.length||!unfinished} onClick={()=>void save()}>{saved?'Retry unfinished':versionOf?'Save new version':'Save files'}</Button></>}>
  <div className="files-dialog stack">{storage==='external'&&<FileNotice warning>{externalWarning}<br/>Choose the file to check it on this device. Its contents will not be uploaded.</FileNotice>}
   <div className="file-dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)choose(e.dataTransfer.files);}}><input ref={picker} className="sr-only" type="file" aria-label={storage==='external'?'Choose shared-drive files to check':'Choose files to upload'} accept={storage==='managed'?fileAccept:undefined} multiple={!versionOf} onChange={e=>{choose(e.target.files);e.target.value='';}} disabled={busy}/>{storage==='managed'?<Upload size={25}/>:<Folder size={25}/>}<h3>{storage==='managed'?'Choose files or drop them here':'Choose the file from your shared drive'}</h3><p>{storage==='managed'?'25 MiB per file · 64 items or 250 MiB in one batch':'Files up to 2 GiB can be checked locally.'}</p><Button variant="secondary" disabled={busy} onClick={()=>picker.current?.click()}><Plus size={16}/> Choose files</Button></div>
   {storage==='managed'&&<p className="field-hint">PDF, DOCX, XLSX, PPTX, RTF, TXT, CSV, PNG, JPEG and WebP</p>}
   {notice&&<FileNotice warning>{notice}</FileNotice>}
   <div className="upload-list">{rows.map(r=>{const tooLarge=r.file.size>(r.storage==='managed'?uploadLimit:externalLimit),unsupported=r.storage==='managed'&&!supported.includes(extension(r.file.name));return <article className={'upload-item '+(r.state==='saved'?'is-saved':'')} key={r.id}><div className="upload-item-heading"><FileIcon name={r.file.name}/><div><strong>{r.file.name}</strong><span className="muted">{bytesLabel(r.file.size)} · {r.storage==='managed'?'Uploaded file':'Shared-drive reference'}</span></div>{r.state==='saved'?<Badge tone="success"><Check size={13}/> Saved</Badge>:<Button variant="ghost" aria-label={(r.locked?'Cancel attempt for ':'Remove ')+r.file.name} busy={cancelling.includes(r.id)} onClick={()=>void cancelRow(r)}><Trash2 size={16}/></Button>}</div>
    {r.state!=='saved'&&<><div className="form-row"><Field label="Document reference" hint="A unique reference that connects this document with its work."><Input value={r.reference} maxLength={128} disabled={busy||r.locked||!!versionOf} onChange={e=>update(r.id,{reference:e.target.value})} placeholder="For example, HR-001"/></Field><Field label="Purpose"><Select value={r.kind} disabled={busy||r.locked||!!versionOf} onChange={e=>update(r.id,{kind:e.target.value as Row['kind']})}><option value="source" disabled={!manager}>Source</option><option value="output">Output</option></Select></Field></div>
     {!taskId&&<Field label="Link to work" hint="You can link this file to more tasks after it is saved."><Select value={r.taskId} disabled={busy||r.locked} onChange={e=>update(r.id,{taskId:e.target.value})}><option value="" disabled={!manager}>{manager?'Project file · no task yet':'Choose your assigned task'}</option>{activeTasks.map(t=><option key={t.id} value={t.id}>{taskName(project,t.id)}</option>)}</Select></Field>}
     {r.storage==='external'&&<Field label="Shared-drive location" hint="A Mac, Windows or shared-drive path. Other people need access to this location."><Input value={r.path} maxLength={4096} disabled={busy||r.locked} onChange={e=>update(r.id,{path:e.target.value})} placeholder="/Volumes/Shared/Project/document.pdf"/></Field>}
     {tooLarge&&<FileNotice warning action={r.storage==='managed'&&!r.locked?<Button variant="secondary" onClick={()=>{update(r.id,{storage:'external'});setStorage('external');}}>Keep on shared drive</Button>:undefined}>{r.storage==='managed'?'This file is larger than 25 MiB.':'This file is larger than the 2 GiB local check limit. Choose a smaller file.'}</FileNotice>}
     {unsupported&&<FileNotice warning action={!r.locked?<Button variant="secondary" onClick={()=>{update(r.id,{storage:'external'});setStorage('external');}}>Keep on shared drive</Button>:undefined}>This file type cannot be uploaded. Choose a supported file, or keep it on your shared drive.</FileNotice>}
     {['preparing','uploading'].includes(r.state)&&<div className="upload-progress" role="status"><div className="files-storage-track"><span style={{width:(r.file.size?r.completed/r.file.size*100:0)+'%'}}/></div><span>{r.state==='preparing'?'Preparing your file…':bytesLabel(r.completed)+' of '+bytesLabel(r.file.size)+' saved'}</span></div>}
     {r.error!==undefined&&<FileNotice error={r.error}/>}
    </>}
   </article>;})}</div>
  </div>
 </Modal>;
}
