import { constants } from 'node:fs';
import { chmod, lstat, mkdir, open, readdir, rename, unlink } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { join } from 'node:path';
import { sealCheckpoint, openCheckpoint, RETENTION_MS } from './recovery-policy.mjs';
import { RETENTION_MARGIN_MS } from './recovery-expiry.mjs';

export const CHECKPOINT_BYTES = 64 * 1024 * 1024;
// 100 workspaces × 288 five-minute points/day × 30 days × two files, plus
// interrupted writes. Explicit local capacity; never silently discard points.
export const RECOVERY_RECORD_MAX_FILES=2_000_000;
export const CHECKPOINT_ID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
export function opaqueId(value) { if (typeof value !== 'string' || !CHECKPOINT_ID.test(value)) throw new Error('Invalid opaque identifier'); return value; }
export function checkpointIndex(value) {
  const keys = ['version','workspaceId','checkpointId','capturedAt','backupLabel','controlBackupLabel','walTarget'];
  if (!value || Object.keys(value).sort().join() !== keys.sort().join() || value.version !== 1) throw new Error('Invalid recovery index');
  opaqueId(value.workspaceId); opaqueId(value.checkpointId);
  if (!Number.isFinite(Date.parse(value.capturedAt)) || !/^\d{8}-\d{6}F$/.test(value.backupLabel) || !/^\d{8}-\d{6}F$/.test(value.controlBackupLabel) ||
    value.walTarget !== `ukda_cp_${value.checkpointId.replaceAll('-', '_')}`) throw new Error('Invalid recovery index');
  return value;
}
async function directory(path) {
  await mkdir(path, {recursive:true,mode:0o700});
  const stat=await lstat(path);
  if(!stat.isDirectory() || stat.isSymbolicLink() || process.getuid && stat.uid !== process.getuid()) throw new Error('Recovery directory ownership mismatch');
  await chmod(path,0o700);
}
async function syncDirectory(path) { const file=await open(path,constants.O_RDONLY);try{await file.sync();}finally{await file.close();} }
async function readPrivate(path,limit=CHECKPOINT_BYTES) {
  const file=await open(path,constants.O_RDONLY|constants.O_NOFOLLOW);
  try {const stat=await file.stat();if(!stat.isFile()||stat.size>limit||stat.mode&0o077||process.getuid&&stat.uid!==process.getuid())throw new Error('Invalid private recovery file');return await file.readFile('utf8');}
  finally{await file.close();}
}
async function writeAtomic(path,text) {
  if(Buffer.byteLength(text)>CHECKPOINT_BYTES)throw new Error('Recovery record exceeds limit');
  const temporary=`${path}.${randomUUID()}.tmp`,file=await open(temporary,constants.O_WRONLY|constants.O_CREAT|constants.O_EXCL|constants.O_NOFOLLOW,0o600);
  try{await file.writeFile(text,'utf8');await file.sync();}finally{await file.close();}
  try{await rename(temporary,path);}catch(error){await unlink(temporary).catch(()=>{});throw error;}
}
export class RecoveryRecords {
  constructor(path,secret){this.path=path;this.secret=secret;}
  base(workspaceId,checkpointId){return join(this.path,`${opaqueId(workspaceId)}.${opaqueId(checkpointId)}`);}
  async save(index,value){
    checkpointIndex(index);await directory(this.path);const base=this.base(index.workspaceId,index.checkpointId);
    // IDs are freshly generated by the CLI. Refuse accidental replacement of a
    // previously completed record even when the invocation is repeated.
    try{await lstat(`${base}.sealed`);throw new Error('Recovery checkpoint already exists');}catch(error){if(error.code!=='ENOENT')throw error;}
    await writeAtomic(`${base}.sealed`,sealCheckpoint(value,this.secret,index.workspaceId,index.checkpointId));
    await writeAtomic(`${base}.json`,JSON.stringify(index));await syncDirectory(this.path);
  }
  async read(workspaceId,checkpointId){
    const base=this.base(workspaceId,checkpointId),index=checkpointIndex(JSON.parse(await readPrivate(`${base}.json`,4096)));
    if(index.workspaceId!==workspaceId||index.checkpointId!==checkpointId)throw new Error('Recovery index mismatch');
    return {index,value:openCheckpoint(await readPrivate(`${base}.sealed`),this.secret,workspaceId,checkpointId)};
  }
  async list(){
    await directory(this.path);const entries=await readdir(this.path);if(entries.length>RECOVERY_RECORD_MAX_FILES)throw new Error('Recovery directory exceeds limit');
    const values=[];for(const name of entries)if(name.endsWith('.json')){
      const parts=name.split('.');if(parts.length!==3||!CHECKPOINT_ID.test(parts[0])||!CHECKPOINT_ID.test(parts[1]))continue;
      const value=checkpointIndex(JSON.parse(await readPrivate(join(this.path,name),4096)));
      if(`${value.workspaceId}.${value.checkpointId}.json`!==name)throw new Error('Recovery index mismatch');values.push(value);
    }return values;
  }
  async remove(workspaceId,checkpointId){
    const base=this.base(workspaceId,checkpointId);
    for(const suffix of ['.json','.sealed']){const path=`${base}${suffix}`;
      try{const stat=await lstat(path);if(!stat.isFile()||stat.isSymbolicLink()||process.getuid&&stat.uid!==process.getuid())throw new Error('Recovery file ownership mismatch');await unlink(path);}catch(error){if(error.code!=='ENOENT')throw error;}}
    await syncDirectory(this.path);
  }
  async expire(now=Date.now(),all=false){
    if(!Number.isFinite(now))throw new Error('Invalid expiry time');await directory(this.path);let removed=0;
    const entries=await readdir(this.path);if(entries.length>RECOVERY_RECORD_MAX_FILES)throw new Error('Recovery directory exceeds limit');
    for(const name of entries){const p=name.split('.'),completed=p.length===3&&['sealed','json'].includes(p[2]),temporary=p.length===5&&['sealed','json'].includes(p[2])&&CHECKPOINT_ID.test(p[3])&&p[4]==='tmp';
      if(!CHECKPOINT_ID.test(p[0])||!CHECKPOINT_ID.test(p[1])||!completed&&!temporary)continue;
      const path=join(this.path,name),stat=await lstat(path);if(!stat.isFile()||stat.isSymbolicLink()||process.getuid&&stat.uid!==process.getuid())throw new Error('Recovery file ownership mismatch');
      if(all||stat.mtimeMs+RETENTION_MS-RETENTION_MARGIN_MS<=now){await unlink(path);removed++;}}
    await syncDirectory(this.path);return removed;
  }
  async removeWorkspace(workspaceId){
    opaqueId(workspaceId);await directory(this.path);
    // Includes an encrypted record left before its index was committed.
    const entries=await readdir(this.path),ids=new Set();if(entries.length>RECOVERY_RECORD_MAX_FILES)throw new Error('Recovery directory exceeds limit');
    for(const name of entries){const parts=name.split('.');if(parts[0]===workspaceId&&parts.length===3&&CHECKPOINT_ID.test(parts[1])&&['sealed','json'].includes(parts[2]))ids.add(parts[1]);}
    for(const id of ids)await this.remove(workspaceId,id);
    for(const name of entries){const parts=name.split('.');if(parts[0]===workspaceId&&parts.length===5&&CHECKPOINT_ID.test(parts[1])&&['sealed','json'].includes(parts[2])&&CHECKPOINT_ID.test(parts[3])&&parts[4]==='tmp'){
      const path=join(this.path,name),stat=await lstat(path);if(!stat.isFile()||stat.isSymbolicLink()||process.getuid&&stat.uid!==process.getuid())throw new Error('Recovery file ownership mismatch');await unlink(path);}}
    await syncDirectory(this.path);return ids.size;
  }
}
export async function repositorySecret(path){
  const text=await readPrivate(path,16384),matches=[...text.matchAll(/^repo1-cipher-pass=([a-f0-9]{64})$/gm)];
  if(matches.length!==1)throw new Error('Invalid repository secret configuration');return matches[0][1];
}
