import { identifier } from '../shared/contracts.js';
import { AuthenticatedHttp } from './auth-controller.js';
import { FileClientError } from './files-crypto.js';
import { storedFileBulk,type StoredFileBulk } from './files-bulk-crypto.js';

/** Only bounded authenticated ciphertext is durable. Files remain in the existing encrypted upload store. */
export class IndexedFileBulkStore {
 private constructor(readonly origin:string,private readonly database:IDBDatabase){database.onversionchange=()=>database.close();}
 static async open(origin:string,name='maqbool-file-bulk-v1',factory:IDBFactory|undefined=globalThis.indexedDB):Promise<IndexedFileBulkStore>{const accepted=new AuthenticatedHttp(origin).origin;if(!factory)throw new FileClientError('STORAGE');return new Promise((resolve,reject)=>{let settled=false;const r=factory.open(name,1);r.onblocked=r.onerror=()=>{settled=true;reject(new FileClientError('STORAGE'));};r.onupgradeneeded=()=>r.result.createObjectStore('batches');r.onsuccess=()=>settled?r.result.close():resolve(new IndexedFileBulkStore(accepted,r.result));});}
 private key(workspaceId:string,batchId:string){return `${this.origin}:${identifier.parse(workspaceId)}:${identifier.parse(batchId)}`;}
 private parse(value:unknown){const r=storedFileBulk.parse(value);if(r.origin!==this.origin)throw new FileClientError('CONFLICT');return r;}
 private transaction<T>(mode:IDBTransactionMode,action:(store:IDBObjectStore,done:(value:T)=>void,fail:(error:unknown)=>void)=>void):Promise<T>{return new Promise((resolve,reject)=>{let tx:IDBTransaction;try{tx=this.database.transaction('batches',mode,mode==='readwrite'?{durability:'strict'}:{});}catch{reject(new FileClientError('STORAGE'));return;}let result:T,finished=false,error:unknown;const fail=(e:unknown)=>{error=e;try{tx.abort();}catch{reject(e);}};tx.onabort=()=>reject(error??new FileClientError('STORAGE'));tx.oncomplete=()=>finished?resolve(result):reject(new FileClientError('STORAGE'));try{action(tx.objectStore('batches'),v=>{result=v;finished=true;},fail);}catch(e){fail(e);}});}
 get(workspaceId:string,batchId:string):Promise<StoredFileBulk|undefined>{return this.transaction('readonly',(s,done,fail)=>{const r=s.get(this.key(workspaceId,batchId));r.onsuccess=()=>{try{done(r.result===undefined?undefined:this.parse(r.result));}catch(e){fail(e);}};});}
 put(value:StoredFileBulk,expectedRevision:string|null):Promise<void>{const record=this.parse(value);return this.transaction('readwrite',(s,done,fail)=>{const r=s.get(this.key(record.workspaceId,record.batchId));r.onsuccess=()=>{try{if(r.result!==undefined){const before=this.parse(r.result);if(before.revision!==expectedRevision||BigInt(record.revision)!==BigInt(before.revision)+1n)throw new FileClientError('CONFLICT');s.put(record,this.key(record.workspaceId,record.batchId));done(undefined);}else{if(expectedRevision!==null||record.revision!=='0')throw new FileClientError('CONFLICT');const count=s.count();count.onsuccess=()=>{if(count.result>=8)fail(new FileClientError('STORAGE'));else{s.add(record,this.key(record.workspaceId,record.batchId));done(undefined);}};}}catch(e){fail(e);}};});}
 list(scope:{workspaceId:string;accountId:string;deviceId:string}):Promise<StoredFileBulk[]>{return this.transaction('readonly',(s,done,fail)=>{const r=s.getAll();r.onsuccess=()=>{try{done(r.result.map(v=>this.parse(v)).filter(v=>v.workspaceId===scope.workspaceId&&v.accountId===scope.accountId&&v.deviceId===scope.deviceId));}catch(e){fail(e);}};});}
 remove(workspaceId:string,batchId:string):Promise<void>{return this.transaction('readwrite',(s,done)=>{s.delete(this.key(workspaceId,batchId));done(undefined);});}
 forgetDevice(scope:{workspaceId:string;accountId:string;deviceId:string}):Promise<void>{return this.transaction('readwrite',(s,done,fail)=>{const r=s.openCursor();r.onsuccess=()=>{try{const c=r.result;if(!c){done(undefined);return;}const v=this.parse(c.value);if(v.workspaceId===scope.workspaceId&&v.accountId===scope.accountId&&v.deviceId===scope.deviceId)c.delete();c.continue();}catch(e){fail(e);}};});}
 close(){this.database.close();}
}
